In [3]:
import pandas as pd
import numpy as np

In [4]:
pip install nltk pandas numpy

Requirement already satisfied: nltk in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (3.9.1)
Requirement already satisfied: pandas in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (2.3.0)
Requirement already satisfied: numpy in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (1.26.4)
Requirement already satisfied: click in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import nltk

nltk.download('punkt_tan')
nltk.download('wordnet')

[nltk_data] Error loading punkt_tan: Package 'punkt_tan' not found in
[nltk_data]     index
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

NLTK,
Spacy - NLP Techniques or library

BERT
Transformer
Word Embedding                  "this and above is this Deep Learning."
RNN, LSTM RNN, GRU
Text processing- word2vec, Avgword2vec
Bow,TFIDF,Unigram
Tokenization,Lemmatization

In [6]:
c = """hello welcome,I love Python  ,
I Learn AI/ML  ,also learn Python.
sdfsfsfklsdf.sdfsd  ,dsfsdf!  ,dfs  ,sga.=sdf
"""

In [7]:
print(c)

hello welcome,I love Python  ,
I Learn AI/ML  ,also learn Python.
sdfsfsfklsdf.sdfsd  ,dsfsdf!  ,dfs  ,sga.=sdf

In [8]:
from nltk.tokenize import sent_tokenize
document = sent_tokenize(c)
document

['hello welcome,I love Python  ,\nI Learn AI/ML  ,also learn Python.',
 'sdfsfsfklsdf.sdfsd  ,dsfsdf!',
 ',dfs  ,sga.=sdf']

In [9]:
for sentence in document:
    print(sentence,"------------")

hello welcome,I love Python  ,
I Learn AI/ML  ,also learn Python. ------------
sdfsfsfklsdf.sdfsd  ,dsfsdf! ------------
,dfs  ,sga.=sdf ------------

In [10]:
from nltk.tokenize import word_tokenize
word_tokenize(c)

['hello',
 'welcome',
 ',',
 'I',
 'love',
 'Python',
 ',',
 'I',
 'Learn',
 'AI/ML',
 ',',
 'also',
 'learn',
 'Python',
 '.',
 'sdfsfsfklsdf.sdfsd',
 ',',
 'dsfsdf',
 '!',
 ',',
 'dfs',
 ',',
 'sga.=sdf']

In [11]:
from nltk.tokenize import wordpunct_tokenize

In [12]:
word_token = word_tokenize(c)
word_token

['hello',
 'welcome',
 ',',
 'I',
 'love',
 'Python',
 ',',
 'I',
 'Learn',
 'AI/ML',
 ',',
 'also',
 'learn',
 'Python',
 '.',
 'sdfsfsfklsdf.sdfsd',
 ',',
 'dsfsdf',
 '!',
 ',',
 'dfs',
 ',',
 'sga.=sdf']

In [13]:
from nltk.tokenize import TreebankWordTokenizer,TreebankWordDetokenizer

In [14]:
tokenizer = TreebankWordTokenizer()
dtokenizer = TreebankWordDetokenizer()

In [15]:
corpus = """hello welcome,I love Python  ,
I Learn AI/ML  ,also learn Python.
sdfsfsfklsdf.sdfsd  ,dsfsdf!  ,dfs  ,sga.=sdf
"""
a = tokenizer.tokenize(corpus)
dtokenizer.tokenize(a)

'hello welcome, I love Python, I Learn AI/ML, also learn Python. sdfsfsfklsdf.sdfsd, dsfsdf!, dfs, sga.=sdf'

In [16]:
words = ['Writing','write',"writen",'play','played','playing','run','running','view','cry','cries','finally','finalized']

PorterStemmer

In [17]:
from nltk.stem import PorterStemmer

In [18]:
stemming = PorterStemmer()

In [19]:
for word in words:
    print(f'{word} ---> {stemming.stem(word)}')

Writing ---> write
write ---> write
writen ---> writen
play ---> play
played ---> play
playing ---> play
run ---> run
running ---> run
view ---> view
cry ---> cri
cries ---> cri
finally ---> final
finalized ---> final

In [20]:
stemming.stem('congratulations')

'congratul'

In [21]:
stemming.stem("sitting")

'sit'

Regexpstemmer class

In [22]:
from nltk.stem import RegexpStemmer
reg_stemmer = RegexpStemmer(regexp='ing$|s$|e$|able$|ed$|ies$',min=4)

In [23]:
reg_stemmer.stem('')

''

Snowball Stemmer

In [24]:
from nltk.stem import SnowballStemmer

In [25]:
snowball = SnowballStemmer('english')

In [26]:
for word in words:
    print(f'{word} ====> {snowball.stem(word)}')

Writing ====> write
write ====> write
writen ====> writen
play ====> play
played ====> play
playing ====> play
run ====> run
running ====> run
view ====> view
cry ====> cri
cries ====> cri
finally ====> final
finalized ====> final

Wordnet Lemmatizer

pos-None -n (default)

verb -v 

adjective -a 

adverb -r

In [27]:
from nltk.stem import WordNetLemmatizer

In [28]:
lemmatizer = WordNetLemmatizer()

In [29]:
lemmatizer.lemmatize('playing',pos='v')

KeyboardInterrupt:

In [ ]:
for word in words:
    print(f'{word} ====> {lemmatizer.lemmatize(word,pos="v")}')

Writing ====> Writing
write ====> write
writen ====> writen
play ====> play
played ====> play
playing ====> play
run ====> run
running ====> run
view ====> view
cry ====> cry
cries ====> cry
finally ====> finally
finalized ====> finalize

In [ ]:
print(lemmatizer.lemmatize('worse',pos='a'),
lemmatizer.lemmatize('better',pos='a'),
lemmatizer.lemmatize('best',pos='a'),
lemmatizer.lemmatize('good',pos='a'),
lemmatizer.lemmatize('better',pos='a'),
lemmatizer.lemmatize('best',pos='a'))

bad good best good good best

In [ ]:
lemmatizer.lemmatize('loudly',pos='r')

'loudly'

In [ ]:
lemmatizer.lemmatize('Fortunately',pos='r')

'Fortunately'

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
print(stopwords.words('german'))
print(stopwords.words('english'))
print(stopwords.words('french'))
print(stopwords.words('spanish'))
print(stopwords.words('portuguese'))
print(stopwords.words('arabic'))
print(stopwords.words('russian'))
print(stopwords.words('italian'))
print(stopwords.words('dutch'))
print(stopwords.words('swedish'))
print(stopwords.words('turkish'))
print(stopwords.words('chinese'))

['aber', 'alle', 'allem', 'allen', 'aller', 'alles', 'als', 'also', 'am', 'an', 'ander', 'andere', 'anderem', 'anderen', 'anderer', 'anderes', 'anderm', 'andern', 'anderr', 'anders', 'auch', 'auf', 'aus', 'bei', 'bin', 'bis', 'bist', 'da', 'damit', 'dann', 'der', 'den', 'des', 'dem', 'die', 'das', 'dass', 'daß', 'derselbe', 'derselben', 'denselben', 'desselben', 'demselben', 'dieselbe', 'dieselben', 'dasselbe', 'dazu', 'dein', 'deine', 'deinem', 'deinen', 'deiner', 'deines', 'denn', 'derer', 'dessen', 'dich', 'dir', 'du', 'dies', 'diese', 'diesem', 'diesen', 'dieser', 'dieses', 'doch', 'dort', 'durch', 'ein', 'eine', 'einem', 'einen', 'einer', 'eines', 'einig', 'einige', 'einigem', 'einigen', 'einiger', 'einiges', 'einmal', 'er', 'ihn', 'ihm', 'es', 'etwas', 'euer', 'eure', 'eurem', 'euren', 'eurer', 'eures', 'für', 'gegen', 'gewesen', 'hab', 'habe', 'haben', 'hat', 'hatte', 'hatten', 'hier', 'hin', 'hinter', 'ich', 'mich', 'mir', 'ihr', 'ihre', 'ihrem', 'ihren', 'ihrer', 'ihres', 'euch', 'im', 'in', 'indem', 'ins', 'ist', 'jede', 'jedem', 'jeden', 'jeder', 'jedes', 'jene', 'jenem', 'jenen', 'jener', 'jenes', 'jetzt', 'kann', 'kein', 'keine', 'keinem', 'keinen', 'keiner', 'keines', 'können', 'könnte', 'machen', 'man', 'manche', 'manchem', 'manchen', 'mancher', 'manches', 'mein', 'meine', 'meinem', 'meinen', 'meiner', 'meines', 'mit', 'muss', 'musste', 'nach', 'nicht', 'nichts', 'noch', 'nun', 'nur', 'ob', 'oder', 'ohne', 'sehr', 'sein', 'seine', 'seinem', 'seinen', 'seiner', 'seines', 'selbst', 'sich', 'sie', 'ihnen', 'sind', 'so', 'solche', 'solchem', 'solchen', 'solcher', 'solches', 'soll', 'sollte', 'sondern', 'sonst', 'über', 'um', 'und', 'uns', 'unsere', 'unserem', 'unseren', 'unser', 'unseres', 'unter', 'viel', 'vom', 'von', 'vor', 'während', 'war', 'waren', 'warst', 'was', 'weg', 'weil', 'weiter', 'welche', 'welchem', 'welchen', 'welcher', 'welches', 'wenn', 'werde', 'werden', 'wie', 'wieder', 'will', 'wir', 'wird', 'wirst', 'wo', 'wollen', 'wollte', 'würde', 'würden', 'zu', 'zum', 'zur', 'zwar', 'zwischen']
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]
['au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle', 'en', 'et', 'eux', 'il', 'ils', 'je', 'la', 'le', 'les', 'leur', 'lui', 'ma', 'mais', 'me', 'même', 'mes', 'moi', 'mon', 'ne', 'nos', 'notre', 'nous', 'on', 'ou', 'par', 'pas', 'pour', 'qu', 'que', 'qui', 'sa', 'se', 'ses', 'son', 'sur', 'ta', 'te', 'tes', 'toi', 'ton', 'tu', 'un', 'une', 'vos', 'votre', 'vous', 'c', 'd', 'j', 'l', 'à', 'm', 'n', 's', 't', 'y', 'été', 'étée', 'étées', 'étés', 'étant', 'étante', 'étants', 'étantes', 'suis', 'es', 'est', 'sommes', 'êtes', 'sont', 'serai', 'seras', 'sera', 'serons', 'serez', 'seront', 'serais', 'serait', 'serions', 'seriez', 'seraient', 'étais', 'était', 'étions', 'étiez', 'étaient', 'fus', 'fut', 'fûmes', 'fûtes', 'furent', 'sois', 'soit', 'soyons', 'soyez', 'soient', 'fusse', 'fusses', 'fût', 'fussions', 'fussiez', 'fussent', 'ayant', 'ayante', 'ayantes', 'ayants', 'eu', 'eue', 'eues', 'eus', 'ai', 'as', 'avons', 'avez', 'ont', 'aurai', 'auras', 'aura', 'aurons', 'aurez', 'auront', 'aurais', 'aurait', 'aurions', 'auriez', 'auraient', 'avais', 'avait', 'avions', 'aviez', 'avaient', 'eut', 'eûmes', 'eûtes', 'eurent', 'aie', 'aies', 'ait', 'ayons', 'ayez', 'aient', 'eusse', 'eusses', 'eût', 'eussions', 'eussiez', 'eussent']
['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los', 'del', 'se', 'las', 'por', 'un', 'para', 'con', 'no', 'una', 'su', 'al', 'lo', 'como', 'más', 'pero', 'sus', 'le', 'ya', 'o', 'este', 'sí', 'porque', 'esta', 'entre', 'cuando', 'muy', 'sin', 'sobre', 'también', 'me', 'hasta', 'hay', 'donde', 'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les', 'ni', 'contra', 'otros', 'ese', 'eso', 'ante', 'ellos', 'e', 'esto', 'mí', 'antes', 'algunos', 'qué', 'unos', 'yo', 'otro', 'otras', 'otra', 'él', 'tanto', 'esa', 'estos', 'mucho', 'quienes', 'nada', 'muchos', 'cual', 'poco', 'ella', 'estar', 'estas', 'algunas', 'algo', 'nosotros', 'mi', 'mis', 'tú', 'te', 'ti', 'tu', 'tus', 'ellas', 'nosotras', 'vosotros', 'vosotras', 'os', 'mío', 'mía', 'míos', 'mías', 'tuyo', 'tuya', 'tuyos', 'tuyas', 'suyo', 'suya', 'suyos', 'suyas', 'nuestro', 'nuestra', 'nuestros', 'nuestras', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'esos', 'esas', 'estoy', 'estás', 'está', 'estamos', 'estáis', 'están', 'esté', 'estés', 'estemos', 'estéis', 'estén', 'estaré', 'estarás', 'estará', 'estaremos', 'estaréis', 'estarán', 'estaría', 'estarías', 'estaríamos', 'estaríais', 'estarían', 'estaba', 'estabas', 'estábamos', 'estabais', 'estaban', 'estuve', 'estuviste', 'estuvo', 'estuvimos', 'estuvisteis', 'estuvieron', 'estuviera', 'estuvieras', 'estuviéramos', 'estuvierais', 'estuvieran', 'estuviese', 'estuvieses', 'estuviésemos', 'estuvieseis', 'estuviesen', 'estando', 'estado', 'estada', 'estados', 'estadas', 'estad', 'he', 'has', 'ha', 'hemos', 'habéis', 'han', 'haya', 'hayas', 'hayamos', 'hayáis', 'hayan', 'habré', 'habrás', 'habrá', 'habremos', 'habréis', 'habrán', 'habría', 'habrías', 'habríamos', 'habríais', 'habrían', 'había', 'habías', 'habíamos', 'habíais', 'habían', 'hube', 'hubiste', 'hubo', 'hubimos', 'hubisteis', 'hubieron', 'hubiera', 'hubieras', 'hubiéramos', 'hubierais', 'hubieran', 'hubiese', 'hubieses', 'hubiésemos', 'hubieseis', 'hubiesen', 'habiendo', 'habido', 'habida', 'habidos', 'habidas', 'soy', 'eres', 'es', 'somos', 'sois', 'son', 'sea', 'seas', 'seamos', 'seáis', 'sean', 'seré', 'serás', 'será', 'seremos', 'seréis', 'serán', 'sería', 'serías', 'seríamos', 'seríais', 'serían', 'era', 'eras', 'éramos', 'erais', 'eran', 'fui', 'fuiste', 'fue', 'fuimos', 'fuisteis', 'fueron', 'fuera', 'fueras', 'fuéramos', 'fuerais', 'fueran', 'fuese', 'fueses', 'fuésemos', 'fueseis', 'fuesen', 'sintiendo', 'sentido', 'sentida', 'sentidos', 'sentidas', 'siente', 'sentid', 'tengo', 'tienes', 'tiene', 'tenemos', 'tenéis', 'tienen', 'tenga', 'tengas', 'tengamos', 'tengáis', 'tengan', 'tendré', 'tendrás', 'tendrá', 'tendremos', 'tendréis', 'tendrán', 'tendría', 'tendrías', 'tendríamos', 'tendríais', 'tendrían', 'tenía', 'tenías', 'teníamos', 'teníais', 'tenían', 'tuve', 'tuviste', 'tuvo', 'tuvimos', 'tuvisteis', 'tuvieron', 'tuviera', 'tuvieras', 'tuviéramos', 'tuvierais', 'tuvieran', 'tuviese', 'tuvieses', 'tuviésemos', 'tuvieseis', 'tuviesen', 'teniendo', 'tenido', 'tenida', 'tenidos', 'tenidas', 'tened']
['a', 'à', 'ao', 'aos', 'aquela', 'aquelas', 'aquele', 'aqueles', 'aquilo', 'as', 'às', 'até', 'com', 'como', 'da', 'das', 'de', 'dela', 'delas', 'dele', 'deles', 'depois', 'do', 'dos', 'e', 'é', 'ela', 'elas', 'ele', 'eles', 'em', 'entre', 'era', 'eram', 'éramos', 'essa', 'essas', 'esse', 'esses', 'esta', 'está', 'estamos', 'estão', 'estar', 'estas', 'estava', 'estavam', 'estávamos', 'este', 'esteja', 'estejam', 'estejamos', 'estes', 'esteve', 'estive', 'estivemos', 'estiver', 'estivera', 'estiveram', 'estivéramos', 'estiverem', 'estivermos', 'estivesse', 'estivessem', 'estivéssemos', 'estou', 'eu', 'foi', 'fomos', 'for', 'fora', 'foram', 'fôramos', 'forem', 'formos', 'fosse', 'fossem', 'fôssemos', 'fui', 'há', 'haja', 'hajam', 'hajamos', 'hão', 'havemos', 'haver', 'hei', 'houve', 'houvemos', 'houver', 'houvera', 'houverá', 'houveram', 'houvéramos', 'houverão', 'houverei', 'houverem', 'houveremos', 'houveria', 'houveriam', 'houveríamos', 'houvermos', 'houvesse', 'houvessem', 'houvéssemos', 'isso', 'isto', 'já', 'lhe', 'lhes', 'mais', 'mas', 'me', 'mesmo', 'meu', 'meus', 'minha', 'minhas', 'muito', 'na', 'não', 'nas', 'nem', 'no', 'nos', 'nós', 'nossa', 'nossas', 'nosso', 'nossos', 'num', 'numa', 'o', 'os', 'ou', 'para', 'pela', 'pelas', 'pelo', 'pelos', 'por', 'qual', 'quando', 'que', 'quem', 'são', 'se', 'seja', 'sejam', 'sejamos', 'sem', 'ser', 'será', 'serão', 'serei', 'seremos', 'seria', 'seriam', 'seríamos', 'seu', 'seus', 'só', 'somos', 'sou', 'sua', 'suas', 'também', 'te', 'tem', 'tém', 'temos', 'tenha', 'tenham', 'tenhamos', 'tenho', 'terá', 'terão', 'terei', 'teremos', 'teria', 'teriam', 'teríamos', 'teu', 'teus', 'teve', 'tinha', 'tinham', 'tínhamos', 'tive', 'tivemos', 'tiver', 'tivera', 'tiveram', 'tivéramos', 'tiverem', 'tivermos', 'tivesse', 'tivessem', 'tivéssemos', 'tu', 'tua', 'tuas', 'um', 'uma', 'você', 'vocês', 'vos']
['إذ', 'إذا', 'إذما', 'إذن', 'أف', 'أقل', 'أكثر', 'ألا', 'إلا', 'التي', 'الذي', 'الذين', 'اللاتي', 'اللائي', 'اللتان', 'اللتيا', 'اللتين', 'اللذان', 'اللذين', 'اللواتي', 'إلى', 'إليك', 'إليكم', 'إليكما', 'إليكن', 'أم', 'أما', 'أما', 'إما', 'أن', 'إن', 'إنا', 'أنا', 'أنت', 'أنتم', 'أنتما', 'أنتن', 'إنما', 'إنه', 'أنى', 'أنى', 'آه', 'آها', 'أو', 'أولاء', 'أولئك', 'أوه', 'آي', 'أي', 'أيها', 'إي', 'أين', 'أين', 'أينما', 'إيه', 'بخ', 'بس', 'بعد', 'بعض', 'بك', 'بكم', 'بكم', 'بكما', 'بكن', 'بل', 'بلى', 'بما', 'بماذا', 'بمن', 'بنا', 'به', 'بها', 'بهم', 'بهما', 'بهن', 'بي', 'بين', 'بيد', 'تلك', 'تلكم', 'تلكما', 'ته', 'تي', 'تين', 'تينك', 'ثم', 'ثمة', 'حاشا', 'حبذا', 'حتى', 'حيث', 'حيثما', 'حين', 'خلا', 'دون', 'ذا', 'ذات', 'ذاك', 'ذان', 'ذانك', 'ذلك', 'ذلكم', 'ذلكما', 'ذلكن', 'ذه', 'ذو', 'ذوا', 'ذواتا', 'ذواتي', 'ذي', 'ذين', 'ذينك', 'ريث', 'سوف', 'سوى', 'شتان', 'عدا', 'عسى', 'عل', 'على', 'عليك', 'عليه', 'عما', 'عن', 'عند', 'غير', 'فإذا', 'فإن', 'فلا', 'فمن', 'في', 'فيم', 'فيما', 'فيه', 'فيها', 'قد', 'كأن', 'كأنما', 'كأي', 'كأين', 'كذا', 'كذلك', 'كل', 'كلا', 'كلاهما', 'كلتا', 'كلما', 'كليكما', 'كليهما', 'كم', 'كم', 'كما', 'كي', 'كيت', 'كيف', 'كيفما', 'لا', 'لاسيما', 'لدى', 'لست', 'لستم', 'لستما', 'لستن', 'لسن', 'لسنا', 'لعل', 'لك', 'لكم', 'لكما', 'لكن', 'لكنما', 'لكي', 'لكيلا', 'لم', 'لما', 'لن', 'لنا', 'له', 'لها', 'لهم', 'لهما', 'لهن', 'لو', 'لولا', 'لوما', 'لي', 'لئن', 'ليت', 'ليس', 'ليسا', 'ليست', 'ليستا', 'ليسوا', 'ما', 'ماذا', 'متى', 'مذ', 'مع', 'مما', 'ممن', 'من', 'منه', 'منها', 'منذ', 'مه', 'مهما', 'نحن', 'نحو', 'نعم', 'ها', 'هاتان', 'هاته', 'هاتي', 'هاتين', 'هاك', 'هاهنا', 'هذا', 'هذان', 'هذه', 'هذي', 'هذين', 'هكذا', 'هل', 'هلا', 'هم', 'هما', 'هن', 'هنا', 'هناك', 'هنالك', 'هو', 'هؤلاء', 'هي', 'هيا', 'هيت', 'هيهات', 'والذي', 'والذين', 'وإذ', 'وإذا', 'وإن', 'ولا', 'ولكن', 'ولو', 'وما', 'ومن', 'وهو', 'يا', 'أبٌ', 'أخٌ', 'حمٌ', 'فو', 'أنتِ', 'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر', 'جانفي', 'فيفري', 'مارس', 'أفريل', 'ماي', 'جوان', 'جويلية', 'أوت', 'كانون', 'شباط', 'آذار', 'نيسان', 'أيار', 'حزيران', 'تموز', 'آب', 'أيلول', 'تشرين', 'دولار', 'دينار', 'ريال', 'درهم', 'ليرة', 'جنيه', 'قرش', 'مليم', 'فلس', 'هللة', 'سنتيم', 'يورو', 'ين', 'يوان', 'شيكل', 'واحد', 'اثنان', 'ثلاثة', 'أربعة', 'خمسة', 'ستة', 'سبعة', 'ثمانية', 'تسعة', 'عشرة', 'أحد', 'اثنا', 'اثني', 'إحدى', 'ثلاث', 'أربع', 'خمس', 'ست', 'سبع', 'ثماني', 'تسع', 'عشر', 'ثمان', 'سبت', 'أحد', 'اثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'أول', 'ثان', 'ثاني', 'ثالث', 'رابع', 'خامس', 'سادس', 'سابع', 'ثامن', 'تاسع', 'عاشر', 'حادي', 'أ', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', 'ء', 'ى', 'آ', 'ؤ', 'ئ', 'أ', 'ة', 'ألف', 'باء', 'تاء', 'ثاء', 'جيم', 'حاء', 'خاء', 'دال', 'ذال', 'راء', 'زاي', 'سين', 'شين', 'صاد', 'ضاد', 'طاء', 'ظاء', 'عين', 'غين', 'فاء', 'قاف', 'كاف', 'لام', 'ميم', 'نون', 'هاء', 'واو', 'ياء', 'همزة', 'ي', 'نا', 'ك', 'كن', 'ه', 'إياه', 'إياها', 'إياهما', 'إياهم', 'إياهن', 'إياك', 'إياكما', 'إياكم', 'إياك', 'إياكن', 'إياي', 'إيانا', 'أولالك', 'تانِ', 'تانِك', 'تِه', 'تِي', 'تَيْنِ', 'ثمّ', 'ثمّة', 'ذانِ', 'ذِه', 'ذِي', 'ذَيْنِ', 'هَؤلاء', 'هَاتانِ', 'هَاتِه', 'هَاتِي', 'هَاتَيْنِ', 'هَذا', 'هَذانِ', 'هَذِه', 'هَذِي', 'هَذَيْنِ', 'الألى', 'الألاء', 'أل', 'أنّى', 'أيّ', 'ّأيّان', 'أنّى', 'أيّ', 'ّأيّان', 'ذيت', 'كأيّ', 'كأيّن', 'بضع', 'فلان', 'وا', 'آمينَ', 'آهِ', 'آهٍ', 'آهاً', 'أُفٍّ', 'أُفٍّ', 'أفٍّ', 'أمامك', 'أمامكَ', 'أوّهْ', 'إلَيْكَ', 'إلَيْكَ', 'إليكَ', 'إليكنّ', 'إيهٍ', 'بخٍ', 'بسّ', 'بَسْ', 'بطآن', 'بَلْهَ', 'حاي', 'حَذارِ', 'حيَّ', 'حيَّ', 'دونك', 'رويدك', 'سرعان', 'شتانَ', 'شَتَّانَ', 'صهْ', 'صهٍ', 'طاق', 'طَق', 'عَدَسْ', 'كِخ', 'مكانَك', 'مكانَك', 'مكانَك', 'مكانكم', 'مكانكما', 'مكانكنّ', 'نَخْ', 'هاكَ', 'هَجْ', 'هلم', 'هيّا', 'هَيْهات', 'وا', 'واهاً', 'وراءَك', 'وُشْكَانَ', 'وَيْ', 'يفعلان', 'تفعلان', 'يفعلون', 'تفعلون', 'تفعلين', 'اتخذ', 'ألفى', 'تخذ', 'ترك', 'تعلَّم', 'جعل', 'حجا', 'حبيب', 'خال', 'حسب', 'خال', 'درى', 'رأى', 'زعم', 'صبر', 'ظنَّ', 'عدَّ', 'علم', 'غادر', 'ذهب', 'وجد', 'ورد', 'وهب', 'أسكن', 'أطعم', 'أعطى', 'رزق', 'زود', 'سقى', 'كسا', 'أخبر', 'أرى', 'أعلم', 'أنبأ', 'حدَث', 'خبَّر', 'نبَّا', 'أفعل به', 'ما أفعله', 'بئس', 'ساء', 'طالما', 'قلما', 'لات', 'لكنَّ', 'ءَ', 'أجل', 'إذاً', 'أمّا', 'إمّا', 'إنَّ', 'أنًّ', 'أى', 'إى', 'أيا', 'ب', 'ثمَّ', 'جلل', 'جير', 'رُبَّ', 'س', 'علًّ', 'ف', 'كأنّ', 'كلَّا', 'كى', 'ل', 'لات', 'لعلَّ', 'لكنَّ', 'لكنَّ', 'م', 'نَّ', 'هلّا', 'وا', 'أل', 'إلّا', 'ت', 'ك', 'لمّا', 'ن', 'ه', 'و', 'ا', 'ي', 'تجاه', 'تلقاء', 'جميع', 'حسب', 'سبحان', 'شبه', 'لعمر', 'مثل', 'معاذ', 'أبو', 'أخو', 'حمو', 'فو', 'مئة', 'مئتان', 'ثلاثمئة', 'أربعمئة', 'خمسمئة', 'ستمئة', 'سبعمئة', 'ثمنمئة', 'تسعمئة', 'مائة', 'ثلاثمائة', 'أربعمائة', 'خمسمائة', 'ستمائة', 'سبعمائة', 'ثمانمئة', 'تسعمائة', 'عشرون', 'ثلاثون', 'اربعون', 'خمسون', 'ستون', 'سبعون', 'ثمانون', 'تسعون', 'عشرين', 'ثلاثين', 'اربعين', 'خمسين', 'ستين', 'سبعين', 'ثمانين', 'تسعين', 'بضع', 'نيف', 'أجمع', 'جميع', 'عامة', 'عين', 'نفس', 'لا سيما', 'أصلا', 'أهلا', 'أيضا', 'بؤسا', 'بعدا', 'بغتة', 'تعسا', 'حقا', 'حمدا', 'خلافا', 'خاصة', 'دواليك', 'سحقا', 'سرا', 'سمعا', 'صبرا', 'صدقا', 'صراحة', 'طرا', 'عجبا', 'عيانا', 'غالبا', 'فرادى', 'فضلا', 'قاطبة', 'كثيرا', 'لبيك', 'معاذ', 'أبدا', 'إزاء', 'أصلا', 'الآن', 'أمد', 'أمس', 'آنفا', 'آناء', 'أنّى', 'أول', 'أيّان', 'تارة', 'ثمّ', 'ثمّة', 'حقا', 'صباح', 'مساء', 'ضحوة', 'عوض', 'غدا', 'غداة', 'قطّ', 'كلّما', 'لدن', 'لمّا', 'مرّة', 'قبل', 'خلف', 'أمام', 'فوق', 'تحت', 'يمين', 'شمال', 'ارتدّ', 'استحال', 'أصبح', 'أضحى', 'آض', 'أمسى', 'انقلب', 'بات', 'تبدّل', 'تحوّل', 'حار', 'رجع', 'راح', 'صار', 'ظلّ', 'عاد', 'غدا', 'كان', 'ما انفك', 'ما برح', 'مادام', 'مازال', 'مافتئ', 'ابتدأ', 'أخذ', 'اخلولق', 'أقبل', 'انبرى', 'أنشأ', 'أوشك', 'جعل', 'حرى', 'شرع', 'طفق', 'علق', 'قام', 'كرب', 'كاد', 'هبّ']
['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его', 'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от', 'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'вдруг', 'ли', 'если', 'уже', 'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'опять', 'уж', 'вам', 'ведь', 'там', 'потом', 'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их', 'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда', 'кто', 'этот', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'здесь', 'этом', 'один', 'почти', 'мой', 'тем', 'чтобы', 'нее', 'сейчас', 'были', 'куда', 'зачем', 'всех', 'никогда', 'можно', 'при', 'наконец', 'два', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них', 'какая', 'много', 'разве', 'три', 'эту', 'моя', 'впрочем', 'хорошо', 'свою', 'этой', 'перед', 'иногда', 'лучше', 'чуть', 'том', 'нельзя', 'такой', 'им', 'более', 'всегда', 'конечно', 'всю', 'между']
['ad', 'al', 'allo', 'ai', 'agli', 'all', 'agl', 'alla', 'alle', 'con', 'col', 'coi', 'da', 'dal', 'dallo', 'dai', 'dagli', 'dall', 'dagl', 'dalla', 'dalle', 'di', 'del', 'dello', 'dei', 'degli', 'dell', 'degl', 'della', 'delle', 'in', 'nel', 'nello', 'nei', 'negli', 'nell', 'negl', 'nella', 'nelle', 'su', 'sul', 'sullo', 'sui', 'sugli', 'sull', 'sugl', 'sulla', 'sulle', 'per', 'tra', 'contro', 'io', 'tu', 'lui', 'lei', 'noi', 'voi', 'loro', 'mio', 'mia', 'miei', 'mie', 'tuo', 'tua', 'tuoi', 'tue', 'suo', 'sua', 'suoi', 'sue', 'nostro', 'nostra', 'nostri', 'nostre', 'vostro', 'vostra', 'vostri', 'vostre', 'mi', 'ti', 'ci', 'vi', 'lo', 'la', 'li', 'le', 'gli', 'ne', 'il', 'un', 'uno', 'una', 'ma', 'ed', 'se', 'perché', 'anche', 'come', 'dov', 'dove', 'che', 'chi', 'cui', 'non', 'più', 'quale', 'quanto', 'quanti', 'quanta', 'quante', 'quello', 'quelli', 'quella', 'quelle', 'questo', 'questi', 'questa', 'queste', 'si', 'tutto', 'tutti', 'a', 'c', 'e', 'i', 'l', 'o', 'ho', 'hai', 'ha', 'abbiamo', 'avete', 'hanno', 'abbia', 'abbiate', 'abbiano', 'avrò', 'avrai', 'avrà', 'avremo', 'avrete', 'avranno', 'avrei', 'avresti', 'avrebbe', 'avremmo', 'avreste', 'avrebbero', 'avevo', 'avevi', 'aveva', 'avevamo', 'avevate', 'avevano', 'ebbi', 'avesti', 'ebbe', 'avemmo', 'aveste', 'ebbero', 'avessi', 'avesse', 'avessimo', 'avessero', 'avendo', 'avuto', 'avuta', 'avuti', 'avute', 'sono', 'sei', 'è', 'siamo', 'siete', 'sia', 'siate', 'siano', 'sarò', 'sarai', 'sarà', 'saremo', 'sarete', 'saranno', 'sarei', 'saresti', 'sarebbe', 'saremmo', 'sareste', 'sarebbero', 'ero', 'eri', 'era', 'eravamo', 'eravate', 'erano', 'fui', 'fosti', 'fu', 'fummo', 'foste', 'furono', 'fossi', 'fosse', 'fossimo', 'fossero', 'essendo', 'faccio', 'fai', 'facciamo', 'fanno', 'faccia', 'facciate', 'facciano', 'farò', 'farai', 'farà', 'faremo', 'farete', 'faranno', 'farei', 'faresti', 'farebbe', 'faremmo', 'fareste', 'farebbero', 'facevo', 'facevi', 'faceva', 'facevamo', 'facevate', 'facevano', 'feci', 'facesti', 'fece', 'facemmo', 'faceste', 'fecero', 'facessi', 'facesse', 'facessimo', 'facessero', 'facendo', 'sto', 'stai', 'sta', 'stiamo', 'stanno', 'stia', 'stiate', 'stiano', 'starò', 'starai', 'starà', 'staremo', 'starete', 'staranno', 'starei', 'staresti', 'starebbe', 'staremmo', 'stareste', 'starebbero', 'stavo', 'stavi', 'stava', 'stavamo', 'stavate', 'stavano', 'stetti', 'stesti', 'stette', 'stemmo', 'steste', 'stettero', 'stessi', 'stesse', 'stessimo', 'stessero', 'stando']

In [ ]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [ ]:
stemmer = PorterStemmer()

In [ ]:
s = nltk.sent_tokenize(c)

In [ ]:
type(s)

list

In [ ]:
for i in range(len(s)):
    w = nltk.word_tokenize(s[i])
    words_not_instopwords = [stemmer.stem(word) for word in w if word not in set(stopwords.words('english'))]
    s[i] = ' '.join(words_not_instopwords)

In [ ]:
for i in s:
    print(i)

hello welcom , i love python , i learn ai/ml , also learn python .
sdfsfsfklsdf.sdfsd , dsfsdf !
, df , sga.=sdf

In [ ]:
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer('english')

for i in range(len(s)):
    W = nltk.word_tokenize(s[i])
    words_not_instopwords = [stemmer.stem(word) for word in W if word not in set(stopwords.words('english'))]
    s[i] = ' '.join(words_not_instopwords)

In [ ]:
for i in s:
    print(i)

hello welcom , love python , learn ai/ml , also learn python .
sdfsfsfklsdf.sdfsd , dsfsdf !
, df , sga.=sdf

In [ ]:
from nltk.stem import WordNetLemmatizer
lammatizer = WordNetLemmatizer()

for i in range(len(s)):
    W = nltk.word_tokenize(s[i])
    words_not_instopwords = [lammatizer.lemmatize(word.lower(),pos='v') for word in W if word not in set(stopwords.words('english'))]
    s[i] = ' '.join(words_not_instopwords)

In [ ]:
for i in s:
    print(i)

hello welcom , love python , learn ai/ml , also learn python .
sdfsfsfklsdf.sdfsd , dsfsdf !
, df , sga.=sdf

In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [ ]:
    for i in range(len(s)):
        W = nltk.word_tokenize(s[i])
        words_not_instopwords = [word for word in W if word not in set(stopwords.words('english'))]
        pos_tags = nltk.pos_tag(words_not_instopwords)
        print(pos_tags)

[('hello', 'NN'), ('welcom', 'NN'), (',', ','), ('love', 'VB'), ('python', 'NN'), (',', ','), ('learn', 'JJ'), ('ai/ml', 'NN'), (',', ','), ('also', 'RB'), ('learn', 'JJ'), ('python', 'NN'), ('.', '.')]
[('sdfsfsfklsdf.sdfsd', 'NN'), (',', ','), ('dsfsdf', 'NN'), ('!', '.')]
[(',', ','), ('df', 'NN'), (',', ','), ('sga.=sdf', 'NN')]

In [ ]:
nltk.pos_tag(['Python', 'is', 'a', 'programming', 'language'])

[('Python', 'NNP'),
 ('is', 'VBZ'),
 ('a', 'DT'),
 ('programming', 'JJ'),
 ('language', 'NN')]

In [ ]:
nltk.pos_tag_sents([nltk.word_tokenize("Taj Mahal is a beautiful Monument in India.")])

[[('Taj', 'NNP'),
  ('Mahal', 'NNP'),
  ('is', 'VBZ'),
  ('a', 'DT'),
  ('beautiful', 'JJ'),
  ('Monument', 'NN'),
  ('in', 'IN'),
  ('India', 'NNP'),
  ('.', '.')]]

In [ ]:
for i in "Taj Mahal is a beautiful Monument in India.".split():
    print(i, "===>", nltk.pos_tag([i]))

Taj ===> [('Taj', 'NN')]
Mahal ===> [('Mahal', 'NN')]
is ===> [('is', 'VBZ')]
a ===> [('a', 'DT')]
beautiful ===> [('beautiful', 'NN')]
Monument ===> [('Monument', 'NN')]
in ===> [('in', 'IN')]
India. ===> [('India.', 'NN')]

Named Entity Recognition

In [ ]:
import nltk
sentence = nltk.word_tokenize("Taj Mahal is a beautiful Monument in India.")
sentence

['Taj', 'Mahal', 'is', 'a', 'beautiful', 'Monument', 'in', 'India', '.']

In [ ]:
w = nltk.pos_tag(sentence)
w

[('Taj', 'NNP'),
 ('Mahal', 'NNP'),
 ('is', 'VBZ'),
 ('a', 'DT'),
 ('beautiful', 'JJ'),
 ('Monument', 'NN'),
 ('in', 'IN'),
 ('India', 'NNP'),
 ('.', '.')]

In [ ]:
nltk.download('maxent_ne_chunker_tab')

[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!

True

In [ ]:
try:
    nltk.ne_chunk(w).draw()
except Exception as e:
    print(e)

Sentiment Analysis

One hot encoding

Word2Vec Practice

In [ ]:
!pip install gensim

Requirement already satisfied: gensim in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from gensim) (7.1.0)
Requirement already satisfied: wrapt in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from smart-open>=1.8.1->gensim) (1.17.2)

In [ ]:
import gensim
from gensim.models import Word2Vec,keyedvectors

In [ ]:
import gensim.downloader as api

In [ ]:
model = api.load("word2vec-google-news- ")

ValueError: Incorrect model/corpus name

In [ ]:
model['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  2.01416016e-02, -1.63085938e-01,  1.35803223e-03,
       -1.44531250e-01, -5.68847656e-02,  4.29687500e-02, -2.46582031e-02,
        1.85546875e-01,  4.47265625e-01,  9.58251953e-03,  1.31835938e-01,
        9.86328125e-02, -1.85546875e-01, -1.00097656e-01, -1.33789062e-01,
       -1.25000000e-01,  2.83203125e-01,  1.23046875e-01,  5.32226562e-02,
       -1.77734375e-01,  8.59375000e-02, -2.18505859e-02,  2.05078125e-02,
       -1.39648438e-01,  2.51464844e-02,  1.38671875e-01, -1.05468750e-01,
        1.38671875e-01,  8.88671875e-02, -7.51953125e-02, -2.13623047e-02,
        1.72851562e-01,  4.63867188e-02, -2.65625000e-01,  8.91113281e-03,
        1.49414062e-01,  3.78417969e-02,  2.38281250e-01, -1.24511719e-01,
       -2.17773438e-01, -1.81640625e-01,  2.97851562e-02,  5.71289062e-02,
       -2.89306641e-02,  1.24511719e-02,  9.66796875e-02, -2.31445312e-01,
        5.81054688e-02,  6.68945312e-02,  7.08007812e-02, -3.08593750e-01,
       -2.14843750e-01,  1.45507812e-01, -4.27734375e-01, -9.39941406e-03,
        1.54296875e-01, -7.66601562e-02,  2.89062500e-01,  2.77343750e-01,
       -4.86373901e-04, -1.36718750e-01,  3.24218750e-01, -2.46093750e-01,
       -3.03649902e-03, -2.11914062e-01,  1.25000000e-01,  2.69531250e-01,
        2.04101562e-01,  8.25195312e-02, -2.01171875e-01, -1.60156250e-01,
       -3.78417969e-02, -1.20117188e-01,  1.15234375e-01, -4.10156250e-02,
       -3.95507812e-02, -8.98437500e-02,  6.34765625e-03,  2.03125000e-01,
        1.86523438e-01,  2.73437500e-01,  6.29882812e-02,  1.41601562e-01,
       -9.81445312e-02,  1.38671875e-01,  1.82617188e-01,  1.73828125e-01,
        1.73828125e-01, -2.37304688e-01,  1.78710938e-01,  6.34765625e-02,
        2.36328125e-01, -2.08984375e-01,  8.74023438e-02, -1.66015625e-01,
       -7.91015625e-02,  2.43164062e-01, -8.88671875e-02,  1.26953125e-01,
       -2.16796875e-01, -1.73828125e-01, -3.59375000e-01, -8.25195312e-02,
       -6.49414062e-02,  5.07812500e-02,  1.35742188e-01, -7.47070312e-02,
       -1.64062500e-01,  1.15356445e-02,  4.45312500e-01, -2.15820312e-01,
       -1.11328125e-01, -1.92382812e-01,  1.70898438e-01, -1.25000000e-01,
        2.65502930e-03,  1.92382812e-01, -1.74804688e-01,  1.39648438e-01,
        2.92968750e-01,  1.13281250e-01,  5.95703125e-02, -6.39648438e-02,
        9.96093750e-02, -2.72216797e-02,  1.96533203e-02,  4.27246094e-02,
       -2.46093750e-01,  6.39648438e-02, -2.25585938e-01, -1.68945312e-01,
        2.89916992e-03,  8.20312500e-02,  3.41796875e-01,  4.32128906e-02,
        1.32812500e-01,  1.42578125e-01,  7.61718750e-02,  5.98144531e-02,
       -1.19140625e-01,  2.74658203e-03, -6.29882812e-02, -2.72216797e-02,
       -4.82177734e-03, -8.20312500e-02, -2.49023438e-02, -4.00390625e-01,
       -1.06933594e-01,  4.24804688e-02,  7.76367188e-02, -1.16699219e-01,
        7.37304688e-02, -9.22851562e-02,  1.07910156e-01,  1.58203125e-01,
        4.24804688e-02,  1.26953125e-01,  3.61328125e-02,  2.67578125e-01,
       -1.01074219e-01, -3.02734375e-01, -5.76171875e-02,  5.05371094e-02,
        5.26428223e-04, -2.07031250e-01, -1.38671875e-01, -8.97216797e-03,
       -2.78320312e-02, -1.41601562e-01,  2.07031250e-01, -1.58203125e-01,
        1.27929688e-01,  1.49414062e-01, -2.24609375e-02, -8.44726562e-02,
        1.22558594e-01,  2.15820312e-01, -2.13867188e-01, -3.12500000e-01,
       -3.73046875e-01,  4.08935547e-03,  1.07421875e-01,  1.06933594e-01,
        7.32421875e-02,  8.97216797e-03, -3.88183594e-02, -1.29882812e-01,
        1.49414062e-01, -2.14843750e-01, -1.83868408e-03,  9.91210938e-02,
        1.57226562e-01, -1.14257812e-01, -2.05078125e-01,  9.91210938e-02,
        3.69140625e-01, -1.97265625e-01,  3.54003906e-02,  1.09375000e-01,
        1.31835938e-01,  1.66992188e-01,  2.35351562e-01,  1.04980469e-01,
       -4.96093750e-01, -1.64062500e-01, -1.56250000e-01, -5.22460938e-02,
        1.03027344e-01,  2.43164062e-01, -1.88476562e-01,  5.07812500e-02,
       -9.37500000e-02, -6.68945312e-02,  2.27050781e-02,  7.61718750e-02,
        2.89062500e-01,  3.10546875e-01, -5.37109375e-02,  2.28515625e-01,
        2.51464844e-02,  6.78710938e-02, -1.21093750e-01, -2.15820312e-01,
       -2.73437500e-01, -3.07617188e-02, -3.37890625e-01,  1.53320312e-01,
        2.33398438e-01, -2.08007812e-01,  3.73046875e-01,  8.20312500e-02,
        2.51953125e-01, -7.61718750e-02, -4.66308594e-02, -2.23388672e-02,
        2.99072266e-02, -5.93261719e-02, -4.66918945e-03, -2.44140625e-01,
       -2.09960938e-01, -2.87109375e-01, -4.54101562e-02, -1.77734375e-01,
       -2.79296875e-01, -8.59375000e-02,  9.13085938e-02,  2.51953125e-01],
      dtype=float32)

In [ ]:
model.most_similar('ball')

[('balls', 0.6992624402046204),
 ('upfield', 0.6896207332611084),
 ('downfield', 0.639072835445404),
 ('dribbler', 0.6218728423118591),
 ('balll', 0.6199931502342224),
 ('dribble', 0.616877555847168),
 ('ball_squirted', 0.6110138297080994),
 ('leftfooted', 0.6020259261131287),
 ('puck', 0.5981723666191101),
 ('mishit', 0.5948783159255981)]

In [ ]:

model.similarity('bottle','man')

0.18008712

In [ ]:
a = model['king'] - model['man'] + model['woman']

In [ ]:
a

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  2.42309570e-01, -3.21777344e-01,  1.45416260e-02,
       -1.59179688e-01, -8.37402344e-02,  1.65039062e-01,  1.58691406e-03,
        3.09570312e-01,  3.16406250e-01,  7.38525391e-03,  2.41210938e-01,
        4.90722656e-02, -9.86328125e-02,  2.90527344e-02,  1.49414062e-01,
       -4.83398438e-02,  2.35595703e-01,  2.21191406e-01,  1.25488281e-01,
       -1.38671875e-01,  1.54296875e-01,  7.18994141e-02,  1.29882812e-01,
       -1.05712891e-01,  6.00585938e-02,  3.14697266e-01,  1.09619141e-01,
        8.49609375e-02,  7.71484375e-02, -2.17285156e-02,  6.11572266e-02,
       -1.89941406e-01,  2.07519531e-01, -1.63085938e-01,  1.13525391e-01,
        2.01171875e-01,  6.06689453e-02,  1.27929688e-01, -3.11279297e-01,
       -2.80151367e-01, -1.55883789e-01,  4.15039062e-02,  9.87854004e-02,
        1.69555664e-01, -3.49121094e-02,  2.08496094e-01, -9.89990234e-02,
        4.39453125e-03, -7.27539062e-02, -4.24804688e-02, -4.09179688e-01,
       -2.76367188e-01,  1.64062500e-01, -5.57617188e-01, -2.02199936e-01,
        2.12158203e-01, -9.81445312e-02,  2.30773926e-01,  2.75878906e-01,
        1.68092728e-01, -4.50439453e-02,  1.71615601e-01, -3.77075195e-01,
       -3.52478027e-03, -3.01513672e-01,  1.74224854e-01,  3.30078125e-01,
        2.00683594e-01,  1.17736816e-01, -1.37695312e-01, -1.07421875e-01,
        8.61816406e-02,  1.06445312e-01,  1.44531250e-01,  3.05175781e-03,
        1.80664062e-02,  3.73535156e-02,  7.32421875e-03,  1.32812500e-01,
        9.61914062e-02,  3.35998535e-01,  1.81152344e-01,  2.40905762e-01,
       -8.49609375e-02, -1.10107422e-01,  2.11914062e-01,  5.85937500e-03,
        1.62109375e-01, -4.15527344e-01,  1.39160156e-01,  1.01562500e-01,
        1.44531250e-01, -1.09375000e-01,  4.88281250e-02,  6.15234375e-02,
       -1.69921875e-01,  3.28369141e-02,  5.56640625e-02,  1.47460938e-01,
       -2.24609375e-02, -2.73925781e-01, -2.81982422e-01, -1.39160156e-01,
       -1.81884766e-01,  9.33532715e-02,  1.21093750e-01, -5.37109375e-03,
       -1.87500000e-01,  3.05175781e-04,  5.52734375e-01, -9.71679688e-02,
       -1.81640625e-01, -1.51855469e-01,  7.76367188e-02, -2.38281250e-01,
       -2.63977051e-02,  2.25555420e-01, -3.02734375e-01,  1.34765625e-01,
        3.23242188e-01,  1.25976562e-01,  3.51562500e-02, -2.04345703e-01,
        2.96142578e-01,  1.03149414e-01, -4.76074219e-03,  1.69189453e-01,
       -3.50585938e-01,  2.46887207e-02, -3.90502930e-01, -2.70507812e-01,
        1.85241699e-02,  1.04492188e-01,  2.84179688e-01,  1.35009766e-01,
       -5.95703125e-02,  1.88232422e-01,  8.88214111e-02,  3.24707031e-02,
       -8.98437500e-02,  5.45043945e-02,  5.65185547e-02,  1.56860352e-01,
       -9.70458984e-03, -7.08007812e-02,  5.71289062e-02, -3.08837891e-01,
       -1.91894531e-01,  4.83398438e-02,  5.22460938e-02, -1.59667969e-01,
       -4.49218750e-02, -7.37304688e-02,  5.51757812e-02,  2.12402344e-01,
        2.05322266e-01, -2.73437500e-02,  7.86132812e-02,  3.19091797e-01,
       -1.56982422e-01, -3.92822266e-01,  4.00390625e-02,  9.93652344e-02,
       -1.97372437e-02, -8.25195312e-02,  2.53906250e-02,  3.10668945e-02,
       -3.63769531e-02,  1.48925781e-02,  2.20703125e-01, -5.98144531e-02,
        6.15234375e-02, -7.14111328e-02, -4.00390625e-02, -1.03515625e-01,
        9.22851562e-02,  2.71789551e-01, -2.30224609e-01, -2.62695312e-01,
       -5.61523438e-01,  1.38549805e-02,  1.09863281e-01,  7.22656250e-02,
        4.58984375e-02, -3.31802368e-02, -8.03833008e-02, -6.10351562e-03,
        2.09960938e-01, -3.86840820e-01,  1.44645691e-01,  8.05664062e-02,
        2.96264648e-01, -1.17187500e-02, -2.34680176e-01,  1.32019043e-01,
        2.53906250e-01, -2.46826172e-01,  1.03759766e-01,  1.14013672e-01,
        1.71875000e-01, -5.61523438e-03,  2.05078125e-01,  6.34765625e-02,
       -4.51293945e-01, -2.26562500e-01, -1.03027344e-01, -1.31469727e-01,
        3.75976562e-02,  2.70996094e-01, -2.39257812e-01,  3.80859375e-02,
       -3.90625000e-02, -9.42382812e-02,  8.30078125e-03,  7.03125000e-02,
        2.75390625e-01,  3.31542969e-01, -1.07421875e-02,  3.72192383e-01,
       -1.24511719e-01,  1.94335938e-01, -1.35620117e-01, -3.09570312e-01,
       -2.36328125e-01, -1.26953125e-02, -2.76855469e-01,  1.57714844e-01,
        3.07617188e-01, -2.32910156e-01,  3.25439453e-01,  1.36718750e-02,
        1.99462891e-01, -2.61840820e-02, -8.08105469e-02, -7.50732422e-02,
       -4.11109924e-02,  1.95556641e-01, -5.64270020e-02, -2.79296875e-01,
       -2.75390625e-01, -4.04296875e-01, -1.75781250e-02, -5.85937500e-03,
       -7.71484375e-02,  1.33789062e-01,  2.36816406e-01,  2.01538086e-01],
      dtype=float32)

In [ ]:
model.most_similar([a])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

Tokenization Practice

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords

In [ ]:
corpus = """hello welcome, to Rudra's AI/ML course. I love Python and I am learning AI/ML."""

In [ ]:
sent_tokenize(corpus)

["hello welcome, to Rudra's AI/ML course.",
 'I love Python and I am learning AI/ML.']

In [ ]:
word_tokenize(corpus)

['hello',
 'welcome',
 ',',
 'to',
 'Rudra',
 "'s",
 'AI/ML',
 'course',
 '.',
 'I',
 'love',
 'Python',
 'and',
 'I',
 'am',
 'learning',
 'AI/ML',
 '.']

In [ ]:
from nltk.tokenize import wordpunct_tokenize

In [ ]:
wordpunct_tokenize(corpus)

['hello',
 'welcome',
 ',',
 'to',
 'Rudra',
 "'",
 's',
 'AI',
 '/',
 'ML',
 'course',
 '.',
 'I',
 'love',
 'Python',
 'and',
 'I',
 'am',
 'learning',
 'AI',
 '/',
 'ML',
 '.']

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [ ]:
stmmer = PorterStemmer()
a = nltk.sent_tokenize(corpus)

In [ ]:
for i in range(len(a)):
    w = nltk.word_tokenize(a[i])
    words_not_instopwords = [stmmer.stem(word) for word in w if word not in set(stopwords.words('english'))]
    a[i] = ' '.join(words_not_instopwords)

In [ ]:
a

["hello welcom , rudra 's ai/ml cours .", 'i love python i learn ai/ml .']

Bag of Words Practicals(BOW)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('spam_messages_1000.csv')

In [ ]:
df

    label                                            message
0    spam  Claim your free vacation package now. Limited ...
1     ham                       Meeting rescheduled to 3 PM.
2     ham               Are you coming to the party tonight?
3    spam  Claim your free vacation package now. Limited ...
4     ham             Can you call me back when you're free?
..    ...                                                ...
995  spam  You have been selected for a cash prize. Reply...
996   ham  Don't forget to bring the documents for the me...
997   ham                      Thanks for your help earlier!
998   ham              Don't worry, everything will be fine.
999  spam               Act now to receive your free iPhone!

[1000 rows x 2 columns]

In [ ]:
import re
import nltk
nltk.download('punkt')
ps = PorterStemmer()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
corpus=[]
for i in range(0,len(df)):
    review = re.sub('[^a-zA-Z]',' ',df['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
print(corpus)
print(len(corpus))

['claim free vacat packag limit time offer', 'meet reschedul pm', 'come parti tonight', 'claim free vacat packag limit time offer', 'call back free', 'meet reschedul pm', 'happi birthday hope great day', 'subscript end renew avoid interrupt', 'meet reschedul pm', 'scam realli', 'get cheap med onlin without prescript visit site', 'urgent account compromis click link secur', 'thank help earlier', 'let catch coffe sometim', 'let catch coffe sometim', 'pre approv loan appli', 'forget bring document meet', 'worri everyth fine', 'thank help earlier', 'worri everyth fine', 'urgent account compromis click link secur', 'scam realli', 'forget bring document meet', 'hey still lunch today', 'let catch coffe sometim', 'subscript end renew avoid interrupt', 'claim free vacat packag limit time offer', 'call back free', 'claim free vacat packag limit time offer', 'late traffic realli bad right', 'urgent account compromis click link secur', 'subscript end renew avoid interrupt', 'thank help earlier', 'claim free vacat packag limit time offer', 'meet reschedul pm', 'get cheap med onlin without prescript visit site', 'late traffic realli bad right', 'pre approv loan appli', 'happi birthday hope great day', 'forget bring document meet', 'hey still lunch today', 'claim free vacat packag limit time offer', 'late traffic realli bad right', 'call back free', 'hey still lunch today', 'claim free vacat packag limit time offer', 'congratul walmart gift card click claim', 'urgent account compromis click link secur', 'forget bring document meet', 'late traffic realli bad right', 'come parti tonight', 'late traffic realli bad right', 'meet reschedul pm', 'call back free', 'scam realli', 'congratul walmart gift card click claim', 'forget bring document meet', 'scam realli', 'act receiv free iphon', 'get cheap med onlin without prescript visit site', 'scam realli', 'hey still lunch today', 'come parti tonight', 'act receiv free iphon', 'get cheap med onlin without prescript visit site', 'congratul walmart gift card click claim', 'happi birthday hope great day', 'come parti tonight', 'act receiv free iphon', 'let catch coffe sometim', 'pre approv loan appli', 'get cheap med onlin without prescript visit site', 'pre approv loan appli', 'worri everyth fine', 'meet reschedul pm', 'hey still lunch today', 'act receiv free iphon', 'congratul walmart gift card click claim', 'select cash prize repli win claim', 'hey still lunch today', 'happi birthday hope great day', 'forget bring document meet', 'pre approv loan appli', 'late traffic realli bad right', 'pre approv loan appli', 'worri everyth fine', 'hey still lunch today', 'claim free vacat packag limit time offer', 'come parti tonight', 'act receiv free iphon', 'late traffic realli bad right', 'hey still lunch today', 'earn day work home experi requir', 'pre approv loan appli', 'act receiv free iphon', 'pre approv loan appli', 'pre approv loan appli', 'meet reschedul pm', 'call back free', 'come parti tonight', 'worri everyth fine', 'select cash prize repli win claim', 'late traffic realli bad right', 'urgent account compromis click link secur', 'meet reschedul pm', 'thank help earlier', 'claim free vacat packag limit time offer', 'happi birthday hope great day', 'meet reschedul pm', 'forget bring document meet', 'come parti tonight', 'call back free', 'earn day work home experi requir', 'subscript end renew avoid interrupt', 'scam realli', 'get cheap med onlin without prescript visit site', 'come parti tonight', 'select cash prize repli win claim', 'earn day work home experi requir', 'claim free vacat packag limit time offer', 'happi birthday hope great day', 'call back free', 'come parti tonight', 'let catch coffe sometim', 'hey still lunch today', 'meet reschedul pm', 'worri everyth fine', 'claim free vacat packag limit time offer', 'meet reschedul pm', 'scam realli', 'let catch coffe sometim', 'call back free', 'late traffic realli bad right', 'congratul walmart gift card click claim', 'earn day work home experi requir', 'call back free', 'happi birthday hope great day', 'get cheap med onlin without prescript visit site', 'claim free vacat packag limit time offer', 'come parti tonight', 'urgent account compromis click link secur', 'scam realli', 'urgent account compromis click link secur', 'hey still lunch today', 'come parti tonight', 'select cash prize repli win claim', 'hey still lunch today', 'pre approv loan appli', 'hey still lunch today', 'forget bring document meet', 'let catch coffe sometim', 'congratul walmart gift card click claim', 'get cheap med onlin without prescript visit site', 'earn day work home experi requir', 'congratul walmart gift card click claim', 'meet reschedul pm', 'select cash prize repli win claim', 'earn day work home experi requir', 'worri everyth fine', 'subscript end renew avoid interrupt', 'forget bring document meet', 'call back free', 'happi birthday hope great day', 'late traffic realli bad right', 'select cash prize repli win claim', 'act receiv free iphon', 'select cash prize repli win claim', 'hey still lunch today', 'happi birthday hope great day', 'let catch coffe sometim', 'claim free vacat packag limit time offer', 'thank help earlier', 'late traffic realli bad right', 'claim free vacat packag limit time offer', 'worri everyth fine', 'get cheap med onlin without prescript visit site', 'hey still lunch today', 'act receiv free iphon', 'late traffic realli bad right', 'pre approv loan appli', 'pre approv loan appli', 'late traffic realli bad right', 'call back free', 'claim free vacat packag limit time offer', 'pre approv loan appli', 'thank help earlier', 'happi birthday hope great day', 'act receiv free iphon', 'come parti tonight', 'late traffic realli bad right', 'pre approv loan appli', 'act receiv free iphon', 'act receiv free iphon', 'act receiv free iphon', 'worri everyth fine', 'late traffic realli bad right', 'late traffic realli bad right', 'call back free', 'scam realli', 'get cheap med onlin without prescript visit site', 'scam realli', 'select cash prize repli win claim', 'come parti tonight', 'forget bring document meet', 'scam realli', 'claim free vacat packag limit time offer', 'late traffic realli bad right', 'scam realli', 'act receiv free iphon', 'happi birthday hope great day', 'urgent account compromis click link secur', 'forget bring document meet', 'subscript end renew avoid interrupt', 'subscript end renew avoid interrupt', 'earn day work home experi requir', 'scam realli', 'claim free vacat packag limit time offer', 'meet reschedul pm', 'meet reschedul pm', 'forget bring document meet', 'meet reschedul pm', 'earn day work home experi requir', 'earn day work home experi requir', 'claim free vacat packag limit time offer', 'act receiv free iphon', 'scam realli', 'come parti tonight', 'late traffic realli bad right', 'come parti tonight', 'claim free vacat packag limit time offer', 'pre approv loan appli', 'get cheap med onlin without prescript visit site', 'earn day work home experi requir', 'happi birthday hope great day', 'call back free', 'late traffic realli bad right', 'call back free', 'pre approv loan appli', 'late traffic realli bad right', 'call back free', 'forget bring document meet', 'select cash prize repli win claim', 'happi birthday hope great day', 'late traffic realli bad right', 'come parti tonight', 'pre approv loan appli', 'thank help earlier', 'meet reschedul pm', 'forget bring document meet', 'act receiv free iphon', 'earn day work home experi requir', 'thank help earlier', 'urgent account compromis click link secur', 'select cash prize repli win claim', 'claim free vacat packag limit time offer', 'urgent account compromis click link secur', 'forget bring document meet', 'call back free', 'come parti tonight', 'meet reschedul pm', 'come parti tonight', 'worri everyth fine', 'claim free vacat packag limit time offer', 'happi birthday hope great day', 'scam realli', 'forget bring document meet', 'urgent account compromis click link secur', 'subscript end renew avoid interrupt', 'hey still lunch today', 'thank help earlier', 'urgent account compromis click link secur', 'call back free', 'come parti tonight', 'let catch coffe sometim', 'come parti tonight', 'hey still lunch today', 'let catch coffe sometim', 'get cheap med onlin without prescript visit site', 'earn day work home experi requir', 'call back free', 'hey still lunch today', 'call back free', 'forget bring document meet', 'call back free', 'get cheap med onlin without prescript visit site', 'act receiv free iphon', 'urgent account compromis click link secur', 'let catch coffe sometim', 'happi birthday hope great day', 'call back free', 'congratul walmart gift card click claim', 'let catch coffe sometim', 'let catch coffe sometim', 'act receiv free iphon', 'earn day work home experi requir', 'scam realli', 'let catch coffe sometim', 'call back free', 'forget bring document meet', 'hey still lunch today', 'hey still lunch today', 'pre approv loan appli', 'urgent account compromis click link secur', 'urgent account compromis click link secur', 'select cash prize repli win claim', 'urgent account compromis click link secur', 'get cheap med onlin without prescript visit site', 'select cash prize repli win claim', 'hey still lunch today', 'get cheap med onlin without prescript visit site', 'hey still lunch today', 'late traffic realli bad right', 'hey still lunch today', 'select cash prize repli win claim', 'late traffic realli bad right', 'earn day work home experi requir', 'subscript end renew avoid interrupt', 'subscript end renew avoid interrupt', 'earn day work home experi requir', 'select cash prize repli win claim', 'earn day work home experi requir', 'urgent account compromis click link secur', 'happi birthday hope great day', 'meet reschedul pm', 'get cheap med onlin without prescript visit site', 'hey still lunch today', 'hey still lunch today', 'meet reschedul pm', 'call back free', 'happi birthday hope great day', 'call back free', 'come parti tonight', 'get cheap med onlin without prescript visit site', 'forget bring document meet', 'thank help earlier', 'late traffic realli bad right', 'hey still lunch today', 'act receiv free iphon', 'act receiv free iphon', 'hey still lunch today', 'subscript end renew avoid interrupt', 'act receiv free iphon', 'call back free', 'congratul walmart gift card click claim', 'happi birthday hope great day', 'worri everyth fine', 'subscript end renew avoid interrupt', 'come parti tonight', 'call back free', 'call back free', 'earn day work home experi requir', 'urgent account compromis click link secur', 'get cheap med onlin without prescript visit site', 'earn day work home experi requir', 'worri everyth fine', 'let catch coffe sometim', 'thank help earlier', 'earn day work home experi requir', 'late traffic realli bad right', 'urgent account compromis click link secur', 'get cheap med onlin without prescript visit site', 'hey still lunch today', 'claim free vacat packag limit time offer', 'earn day work home experi requir', 'act receiv free iphon', 'claim free vacat packag limit time offer', 'let catch coffe sometim', 'hey still lunch today', 'scam realli', 'scam realli', 'claim free vacat packag limit time offer', 'meet reschedul pm', 'earn day work home experi requir', 'come parti tonight', 'call back free', 'come parti tonight', 'subscript end renew avoid interrupt', 'thank help earlier', 'act receiv free iphon', 'scam realli', 'worri everyth fine', 'worri everyth fine', 'pre approv loan appli', 'claim free vacat packag limit time offer', 'act receiv free iphon', 'urgent account compromis click link secur', 'happi birthday hope great day', 'act receiv free iphon', 'come parti tonight', 'worri everyth fine', 'claim free vacat packag limit time offer', 'forget bring document meet', 'pre approv loan appli', 'act receiv free iphon', 'claim free vacat packag limit time offer', 'pre approv loan appli', 'urgent account compromis click link secur', 'late traffic realli bad right', 'earn day work home experi requir', 'forget bring document meet', 'act receiv free iphon', 'earn day work home experi requir', 'come parti tonight', 'congratul walmart gift card click claim', 'worri everyth fine', 'late traffic realli bad right', 'scam realli', 'forget bring document meet', 'forget bring document meet', 'worri everyth fine', 'act receiv free iphon', 'urgent account compromis click link secur', 'meet reschedul pm', 'scam realli', 'forget bring document meet', 'let catch coffe sometim', 'thank help earlier', 'congratul walmart gift card click claim', 'urgent account compromis click link secur', 'forget bring document meet', 'earn day work home experi requir', 'congratul walmart gift card click claim', 'come parti tonight', 'happi birthday hope great day', 'worri everyth fine', 'forget bring document meet', 'act receiv free iphon', 'come parti tonight', 'claim free vacat packag limit time offer', 'get cheap med onlin without prescript visit site', 'pre approv loan appli', 'thank help earlier', 'scam realli', 'select cash prize repli win claim', 'pre approv loan appli', 'congratul walmart gift card click claim', 'let catch coffe sometim', 'forget bring document meet', 'meet reschedul pm', 'urgent account compromis click link secur', 'hey still lunch today', 'urgent account compromis click link secur', 'hey still lunch today', 'worri everyth fine', 'select cash prize repli win claim', 'let catch coffe sometim', 'hey still lunch today', 'pre approv loan appli', 'call back free', 'urgent account compromis click link secur', 'subscript end renew avoid interrupt', 'urgent account compromis click link secur', 'urgent account compromis click link secur', 'pre approv loan appli', 'thank help earlier', 'happi birthday hope great day', 'claim free vacat packag limit time offer', 'act receiv free iphon', 'scam realli', 'pre approv loan appli', 'scam realli', 'late traffic realli bad right', 'happi birthday hope great day', 'come parti tonight', 'late traffic realli bad right', 'meet reschedul pm', 'subscript end renew avoid interrupt', 'let catch coffe sometim', 'scam realli', 'worri everyth fine', 'happi birthday hope great day', 'earn day work home experi requir', 'worri everyth fine', 'let catch coffe sometim', 'meet reschedul pm', 'urgent account compromis click link secur', 'congratul walmart gift card click claim', 'earn day work home experi requir', 'forget bring document meet', 'hey still lunch today', 'come parti tonight', 'act receiv free iphon', 'late traffic realli bad right', 'select cash prize repli win claim', 'congratul walmart gift card click claim', 'meet reschedul pm', 'late traffic realli bad right', 'hey still lunch today', 'scam realli', 'call back free', 'select cash prize repli win claim', 'meet reschedul pm', 'get cheap med onlin without prescript visit site', 'scam realli', 'pre approv loan appli', 'claim free vacat packag limit time offer', 'worri everyth fine', 'act receiv free iphon', 'hey still lunch today', 'forget bring document meet', 'select cash prize repli win claim', 'call back free', 'scam realli', 'scam realli', 'forget bring document meet', 'act receiv free iphon', 'forget bring document meet', 'thank help earlier', 'scam realli', 'earn day work home experi requir', 'urgent account compromis click link secur', 'scam realli', 'meet reschedul pm', 'late traffic realli bad right', 'happi birthday hope great day', 'forget bring document meet', 'act receiv free iphon', 'late traffic realli bad right', 'congratul walmart gift card click claim', 'act receiv free iphon', 'happi birthday hope great day', 'scam realli', 'meet reschedul pm', 'forget bring document meet', 'come parti tonight', 'hey still lunch today', 'earn day work home experi requir', 'subscript end renew avoid interrupt', 'subscript end renew avoid interrupt', 'subscript end renew avoid interrupt', 'let catch coffe sometim', 'hey still lunch today', 'act receiv free iphon', 'subscript end renew avoid interrupt', 'forget bring document meet', 'late traffic realli bad right', 'urgent account compromis click link secur', 'congratul walmart gift card click claim', 'happi birthday hope great day', 'claim free vacat packag limit time offer', 'late traffic realli bad right', 'urgent account compromis click link secur', 'let catch coffe sometim', 'urgent account compromis click link secur', 'let catch coffe sometim', 'pre approv loan appli', 'scam realli', 'late traffic realli bad right', 'act receiv free iphon', 'happi birthday hope great day', 'congratul walmart gift card click claim', 'earn day work home experi requir', 'select cash prize repli win claim', 'earn day work home experi requir', 'get cheap med onlin without prescript visit site', 'claim free vacat packag limit time offer', 'select cash prize repli win claim', 'urgent account compromis click link secur', 'pre approv loan appli', 'let catch coffe sometim', 'congratul walmart gift card click claim', 'congratul walmart gift card click claim', 'get cheap med onlin without prescript visit site', 'call back free', 'get cheap med onlin without prescript visit site', 'congratul walmart gift card click claim', 'earn day work home experi requir', 'let catch coffe sometim', 'subscript end renew avoid interrupt', 'late traffic realli bad right', 'forget bring document meet', 'hey still lunch today', 'earn day work home experi requir', 'pre approv loan appli', 'pre approv loan appli', 'get cheap med onlin without prescript visit site', 'happi birthday hope great day', 'select cash prize repli win claim', 'thank help earlier', 'forget bring document meet', 'meet reschedul pm', 'select cash prize repli win claim', 'get cheap med onlin without prescript visit site', 'meet reschedul pm', 'worri everyth fine', 'urgent account compromis click link secur', 'pre approv loan appli', 'call back free', 'congratul walmart gift card click claim', 'happi birthday hope great day', 'get cheap med onlin without prescript visit site', 'call back free', 'come parti tonight', 'scam realli', 'let catch coffe sometim', 'get cheap med onlin without prescript visit site', 'late traffic realli bad right', 'hey still lunch today', 'let catch coffe sometim', 'pre approv loan appli', 'earn day work home experi requir', 'select cash prize repli win claim', 'forget bring document meet', 'thank help earlier', 'pre approv loan appli', 'pre approv loan appli', 'subscript end renew avoid interrupt', 'hey still lunch today', 'scam realli', 'hey still lunch today', 'act receiv free iphon', 'worri everyth fine', 'happi birthday hope great day', 'thank help earlier', 'meet reschedul pm', 'meet reschedul pm', 'pre approv loan appli', 'earn day work home experi requir', 'meet reschedul pm', 'hey still lunch today', 'urgent account compromis click link secur', 'subscript end renew avoid interrupt', 'get cheap med onlin without prescript visit site', 'congratul walmart gift card click claim', 'get cheap med onlin without prescript visit site', 'act receiv free iphon', 'forget bring document meet', 'let catch coffe sometim', 'scam realli', 'thank help earlier', 'meet reschedul pm', 'let catch coffe sometim', 'urgent account compromis click link secur', 'worri everyth fine', 'hey still lunch today', 'scam realli', 'happi birthday hope great day', 'meet reschedul pm', 'meet reschedul pm', 'happi birthday hope great day', 'thank help earlier', 'meet reschedul pm', 'call back free', 'forget bring document meet', 'subscript end renew avoid interrupt', 'urgent account compromis click link secur', 'come parti tonight', 'late traffic realli bad right', 'call back free', 'come parti tonight', 'pre approv loan appli', 'happi birthday hope great day', 'congratul walmart gift card click claim', 'call back free', 'forget bring document meet', 'scam realli', 'happi birthday hope great day', 'thank help earlier', 'call back free', 'late traffic realli bad right', 'congratul walmart gift card click claim', 'call back free', 'call back free', 'call back 

In [ ]:
##create the Bag of wores model
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv= CountVectorizer(max_features=1000,lowercase=True)
X = cv.fit_transform(corpus).toarray()

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
cv= CountVectorizer(max_features=1000,lowercase=True,binary=True)
X = cv.fit_transform(corpus).toarray()

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
X.shape

(1000, 83)

TF-IDF

In [ ]:
df

    label                                            message
0    spam  Claim your free vacation package now. Limited ...
1     ham                       Meeting rescheduled to 3 PM.
2     ham               Are you coming to the party tonight?
3    spam  Claim your free vacation package now. Limited ...
4     ham             Can you call me back when you're free?
..    ...                                                ...
995  spam  You have been selected for a cash prize. Reply...
996   ham  Don't forget to bring the documents for the me...
997   ham                      Thanks for your help earlier!
998   ham              Don't worry, everything will be fine.
999  spam               Act now to receive your free iPhone!

[1000 rows x 2 columns]

In [ ]:
from nltk.stem import WordNetLemmatizer

In [ ]:
wordlemma = WordNetLemmatizer()

In [ ]:
corpus=[]
for i in range(0,len(df)):
    review = re.sub('[^a-zA-Z]',' ',df['message'][i])
    review = review.lower()
    review = review.split()
    review = [wordlemma.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['claim free vacation package limited time offer',
 'meeting rescheduled pm',
 'coming party tonight',
 'claim free vacation package limited time offer',
 'call back free',
 'meeting rescheduled pm',
 'happy birthday hope great day',
 'subscription ending renew avoid interruption',
 'meeting rescheduled pm',
 'scam really',
 'get cheap med online without prescription visit site',
 'urgent account compromised click link secure',
 'thanks help earlier',
 'let catch coffee sometime',
 'let catch coffee sometime',
 'pre approved loan apply',
 'forget bring document meeting',
 'worry everything fine',
 'thanks help earlier',
 'worry everything fine',
 'urgent account compromised click link secure',
 'scam really',
 'forget bring document meeting',
 'hey still lunch today',
 'let catch coffee sometime',
 'subscription ending renew avoid interruption',
 'claim free vacation package limited time offer',
 'call back free',
 'claim free vacation package limited time offer',
 'late traffic really bad right',
 'urgent account compromised click link secure',
 'subscription ending renew avoid interruption',
 'thanks help earlier',
 'claim free vacation package limited time offer',
 'meeting rescheduled pm',
 'get cheap med online without prescription visit site',
 'late traffic really bad right',
 'pre approved loan apply',
 'happy birthday hope great day',
 'forget bring document meeting',
 'hey still lunch today',
 'claim free vacation package limited time offer',
 'late traffic really bad right',
 'call back free',
 'hey still lunch today',
 'claim free vacation package limited time offer',
 'congratulation walmart gift card click claim',
 'urgent account compromised click link secure',
 'forget bring document meeting',
 'late traffic really bad right',
 'coming party tonight',
 'late traffic really bad right',
 'meeting rescheduled pm',
 'call back free',
 'scam really',
 'congratulation walmart gift card click claim',
 'forget bring document meeting',
 'scam really',
 'act receive free iphone',
 'get cheap med online without prescription visit site',
 'scam really',
 'hey still lunch today',
 'coming party tonight',
 'act receive free iphone',
 'get cheap med online without prescription visit site',
 'congratulation walmart gift card click claim',
 'happy birthday hope great day',
 'coming party tonight',
 'act receive free iphone',
 'let catch coffee sometime',
 'pre approved loan apply',
 'get cheap med online without prescription visit site',
 'pre approved loan apply',
 'worry everything fine',
 'meeting rescheduled pm',
 'hey still lunch today',
 'act receive free iphone',
 'congratulation walmart gift card click claim',
 'selected cash prize reply win claim',
 'hey still lunch today',
 'happy birthday hope great day',
 'forget bring document meeting',
 'pre approved loan apply',
 'late traffic really bad right',
 'pre approved loan apply',
 'worry everything fine',
 'hey still lunch today',
 'claim free vacation package limited time offer',
 'coming party tonight',
 'act receive free iphone',
 'late traffic really bad right',
 'hey still lunch today',
 'earn day working home experience required',
 'pre approved loan apply',
 'act receive free iphone',
 'pre approved loan apply',
 'pre approved loan apply',
 'meeting rescheduled pm',
 'call back free',
 'coming party tonight',
 'worry everything fine',
 'selected cash prize reply win claim',
 'late traffic really bad right',
 'urgent account compromised click link secure',
 'meeting rescheduled pm',
 'thanks help earlier',
 'claim free vacation package limited time offer',
 'happy birthday hope great day',
 'meeting rescheduled pm',
 'forget bring document meeting',
 'coming party tonight',
 'call back free',
 'earn day working home experience required',
 'subscription ending renew avoid interruption',
 'scam really',
 'get cheap med online without prescription visit site',
 'coming party tonight',
 'selected cash prize reply win claim',
 'earn day working home experience required',
 'claim free vacation package limited time offer',
 'happy birthday hope great day',
 'call back free',
 'coming party tonight',
 'let catch coffee sometime',
 'hey still lunch today',
 'meeting rescheduled pm',
 'worry everything fine',
 'claim free vacation package limited time offer',
 'meeting rescheduled pm',
 'scam really',
 'let catch coffee sometime',
 'call back free',
 'late traffic really bad right',
 'congratulation walmart gift card click claim',
 'earn day working home experience required',
 'call back free',
 'happy birthday hope great day',
 'get cheap med online without prescription visit site',
 'claim free vacation package limited time offer',
 'coming party tonight',
 'urgent account compromised click link secure',
 'scam really',
 'urgent account compromised click link secure',
 'hey still lunch today',
 'coming party tonight',
 'selected cash prize reply win claim',
 'hey still lunch today',
 'pre approved loan apply',
 'hey still lunch today',
 'forget bring document meeting',
 'let catch coffee sometime',
 'congratulation walmart gift card click claim',
 'get cheap med online without prescription visit site',
 'earn day working home experience required',
 'congratulation walmart gift card click claim',
 'meeting rescheduled pm',
 'selected cash prize reply win claim',
 'earn day working home experience required',
 'worry everything fine',
 'subscription ending renew avoid interruption',
 'forget bring document meeting',
 'call back free',
 'happy birthday hope great day',
 'late traffic really bad right',
 'selected cash prize reply win claim',
 'act receive free iphone',
 'selected cash prize reply win claim',
 'hey still lunch today',
 'happy birthday hope great day',
 'let catch coffee sometime',
 'claim free vacation package limited time offer',
 'thanks help earlier',
 'late traffic really bad right',
 'claim free vacation package limited time offer',
 'worry everything fine',
 'get cheap med online without prescription visit site',
 'hey still lunch today',
 'act receive free iphone',
 'late traffic really bad right',
 'pre approved loan apply',
 'pre approved loan apply',
 'late traffic really bad right',
 'call back free',
 'claim free vacation package limited time offer',
 'pre approved loan apply',
 'thanks help earlier',
 'happy birthday hope great day',
 'act receive free iphone',
 'coming party tonight',
 'late traffic really bad right',
 'pre approved loan apply',
 'act receive free iphone',
 'act receive free iphone',
 'act receive free iphone',
 'worry everything fine',
 'late traffic really bad right',
 'late traffic really bad right',
 'call back free',
 'scam really',
 'get cheap med online without prescription visit site',
 'scam really',
 'selected cash prize reply win claim',
 'coming party tonight',
 'forget bring document meeting',
 'scam really',
 'claim free vacation package limited time offer',
 'late traffic really bad right',
 'scam really',
 'act receive free iphone',
 'happy birthday hope great day',
 'urgent account compromised click link secure',
 'forget bring document meeting',
 'subscription ending renew avoid interruption',
 'subscription ending renew avoid interruption',
 'earn day working home experience required',
 'scam really',
 'claim free vacation package limited time offer',
 'meeting rescheduled pm',
 'meeting rescheduled pm',
 'forget bring document meeting',
 'meeting rescheduled pm',
 'earn day working home experience required',
 'earn day working home experience required',
 'claim free vacation package limited time offer',
 'act receive free iphone',
 'scam really',
 'coming party tonight',
 'late traffic really bad right',
 'coming party tonight',
 'claim free vacation package limited time offer',
 'pre approved loan apply',
 'get cheap med online without prescription visit site',
 'earn day working home experience required',
 'happy birthday hope great day',
 'call back free',
 'late traffic really bad right',
 'call back free',
 'pre approved loan apply',
 'late traffic really bad right',
 'call back free',
 'forget bring document meeting',
 'selected cash prize reply win claim',
 'happy birthday hope great day',
 'late traffic really bad right',
 'coming party tonight',
 'pre approved loan apply',
 'thanks help earlier',
 'meeting rescheduled pm',
 'forget bring document meeting',
 'act receive free iphone',
 'earn day working home experience required',
 'thanks help earlier',
 'urgent account compromised click link secure',
 'selected cash prize reply win claim',
 'claim free vacation package limited time offer',
 'urgent account compromised click link secure',
 'forget bring document meeting',
 'call back free',
 'coming party tonight',
 'meeting rescheduled pm',
 'coming party tonight',
 'worry everything fine',
 'claim free vacation package limited time offer',
 'happy birthday hope great day',
 'scam really',
 'forget bring document meeting',
 'urgent account compromised click link secure',
 'subscription ending renew avoid interruption',
 'hey still lunch today',
 'thanks help earlier',
 'urgent account compromised click link secure',
 'call back free',
 'coming party tonight',
 'let catch coffee sometime',
 'coming party tonight',
 'hey still lunch today',
 'let catch coffee sometime',
 'get cheap med online without prescription visit site',
 'earn day working home experience required',
 'call back free',
 'hey still lunch today',
 'call back free',
 'forget bring document meeting',
 'call back free',
 'get cheap med online without prescription visit site',
 'act receive free iphone',
 'urgent account compromised click link secure',
 'let catch coffee sometime',
 'happy birthday hope great day',
 'call back free',
 'congratulation walmart gift card click claim',
 'let catch coffee sometime',
 'let catch coffee sometime',
 'act receive free iphone',
 'earn day working home experience required',
 'scam really',
 'let catch coffee sometime',
 'call back free',
 'forget bring document meeting',
 'hey still lunch today',
 'hey still lunch today',
 'pre approved loan apply',
 'urgent account compromised click link secure',
 'urgent account compromised click link secure',
 'selected cash prize reply win claim',
 'urgent account compromised click link secure',
 'get cheap med online without prescription visit site',
 'selected cash prize reply win claim',
 'hey still lunch today',
 'get cheap med online without prescription visit site',
 'hey still lunch today',
 'late traffic really bad right',
 'hey still lunch today',
 'selected cash prize reply win claim',
 'late traffic really bad right',
 'earn day working home experience required',
 'subscription ending renew avoid interruption',
 'subscription ending renew avoid interruption',
 'earn day working home experience required',
 'selected cash prize reply win claim',
 'earn day working home experience required',
 'urgent account compromised click link secure',
 'happy birthday hope great day',
 'meeting rescheduled pm',
 'get cheap med online without prescription visit site',
 'hey still lunch today',
 'hey still lunch today',
 'meeting rescheduled pm',
 'call back free',
 'happy birthday hope great day',
 'call back free',
 'coming party tonight',
 'get cheap med online without prescription visit site',
 'forget bring document meeting',
 'thanks help earlier',
 'late traffic really bad right',
 'hey still lunch today',
 'act receive free iphone',
 'act receive free iphone',
 'hey still lunch today',
 'subscription ending renew avoid interruption',
 'act receive free iphone',
 'call back free',
 'congratulation walmart gift card click claim',
 'happy birthday hope great day',
 'worry everything fine',
 'subscription ending renew avoid interruption',
 'coming party tonight',
 'call back free',
 'call back free',
 'earn day working home experience required',
 'urgent account compromised click link secure',
 'get cheap med online without prescription visit site',
 'earn day working home experience required',
 'worry everything fine',
 'let catch coffee sometime',
 'thanks help earlier',
 'earn day working home experience required',
 'late traffic really bad right',
 'urgent account compromised click link secure',
 'get cheap med online without prescription visit site',
 'hey still lunch today',
 'claim free vacation package limited time offer',
 'earn day working home experience required',
 'act receive free iphone',
 'claim free vacation package limited time offer',
 'let catch coffee sometime',
 'hey still lunch today',
 'scam really',
 'scam really',
 'claim free vacation package limited time offer',
 'meeting rescheduled pm',
 'earn day working home experience required',
 'coming party tonight',
 'call back free',
 'coming party tonight',
 'subscription ending renew avoid interruption',
 'thanks help earlier',
 'act receive free iphone',
 'scam really',
 'worry everything fine',
 'worry everything fine',
 'pre approved loan apply',
 'claim free vacation package limited time offer',
 'act receive free iphone',
 'urgent account compromised click link secure',
 'happy birthday hope great day',
 'act receive free iphone',
 'coming party tonight',
 'worry everything fine',
 'claim free vacation package limited time offer',
 'forget bring document meeting',
 'pre approved loan apply',
 'act receive free iphone',
 'claim free vacation package limited time offer',
 'pre approved loan apply',
 'urgent account compromised click link secure',
 'late traffic really bad right',
 'earn day working home experience required',
 'forget bring document meeting',
 'act receive free iphone',
 'earn day working home experience required',
 'coming party tonight',
 'congratulation walmart gift card click claim',
 'worry everything fine',
 'late traffic really bad right',
 'scam really',
 'forget bring document meeting',
 'forget bring document meeting',
 'worry everything fine',
 'act receive free iphone',
 'urgent account compromised click link secure',
 'meeting rescheduled pm',
 'scam really',
 'forget bring document meeting',
 'let catch coffee sometime',
 'thanks help earlier',
 'congratulation walmart gift card click claim',
 'urgent account compromised click link secure',
 'forget bring document meeting',
 'earn day working home experience required',
 'congratulation walmart gift card click claim',
 'coming party tonight',
 'happy birthday hope great day',
 'worry everything fine',
 'forget bring document meeting',
 'act receive free iphone',
 'coming party tonight',
 'claim free vacation package limited time offer',
 'get cheap med online without prescription visit site',
 'pre approved loan apply',
 'thanks help earlier',
 'scam really',
 'selected cash prize reply win claim',
 'pre approved loan apply',
 'congratulation walmart gift card click claim',
 'let catch coffee sometime',
 'forget bring document meeting',
 'meeting rescheduled pm',
 'urgent account compromised click link secure',
 'hey still lunch today',
 'urgent account compromised click link secure',
 'hey still lunch today',
 'worry everything fine',
 'selected cash prize reply win claim',
 'let catch coffee sometime',
 'hey still lunch today',
 'pre approved loan apply',
 'call back free',
 'urgent account compromised click link secure',
 'subscription ending renew avoid interruption',
 'urgent account compromised click link secure',
 'urgent account compromised click link secure',
 'pre approved loan apply',
 'thanks help earlier',
 'happy birthday hope great day',
 'claim free vacation package limited time offer',
 'act receive free iphone',
 'scam really',
 'pre approved loan apply',
 'scam really',
 'late traffic really bad right',
 'happy birthday hope great day',
 'coming party tonight',
 'late traffic really bad right',
 'meeting rescheduled pm',
 'subscription ending renew avoid interruption',
 'let catch coffee sometime',
 'scam really',
 'worry everything fine',
 'happy birthday hope great day',
 'earn day working home experience required',
 'worry everything fine',
 'let catch coffee sometime',
 'meeting rescheduled pm',
 'urgent account compromised click link secure',
 'congratulation walmart gift card click claim',
 'earn day working home experience required',
 'forget bring document meeting',
 'hey still lunch today',
 'coming party tonight',
 'act receive free iphone',
 'late traffic really bad right',
 'selected cash prize reply win claim',
 'congratulation walmart gift card click claim',
 'meeting rescheduled pm',
 'late traffic really bad right',
 'hey still lunch today',
 'scam really',
 'call back free',
 'selected cash prize reply win claim',
 'meeting rescheduled pm',
 'get cheap med online without prescription visit site',
 'scam really',
 'pre approved loan apply',
 'claim free vacation package limited time offer',
 'worry everything fine',
 'act receive free iphone',
 'hey still lunch today',
 'forget bring document meeting',
 'selected cash prize reply win claim',
 'call back free',
 'scam really',
 'scam really',
 'forget bring document meeting',
 'act receive free iphone',
 'forget bring document meeting',
 'thanks help earlier',
 'scam really',
 'earn day working home experience required',
 'urgent account compromised click link secure',
 'scam really',
 'meeting rescheduled pm',
 'late traffic really bad right',
 'happy birthday hope great day',
 'forget bring document meeting',
 'act receive free iphone',
 'late traffic really bad right',
 'congratulation walmart gift card click claim',
 'act receive free iphone',
 'happy birthday hope great day',
 'scam really',
 'meeting rescheduled pm',
 'forget bring document meeting',
 'coming party tonight',
 'hey still lunch today',
 'earn day working home experience required',
 'subscription ending renew avoid interruption',
 'subscription ending renew avoid interruption',
 'subscription ending renew avoid interruption',
 'let catch coffee sometime',
 'hey still lunch today',
 'act receive free iphone',
 'subscription ending renew avoid interruption',
 'forget bring document meeting',
 'late traffic really bad right',
 'urgent account compromised click link secure',
 'congratulation walmart gift card click claim',
 'happy birthday hope great day',
 'claim free vacation package limited time offer',
 'late traffic really bad right',
 'urgent account compromised click link secure',
 'let catch coffee sometime',
 'urgent account compromised click link secure',
 'let catch coffee sometime',
 'pre approved loan apply',
 'scam really',
 'late traffic really bad right',
 'act receive free iphone',
 'happy birthday hope great day',
 'congratulation walmart gift card click claim',
 'earn day working home experience required',
 'selected cash prize reply win claim',
 'earn day working home experience required',
 'get cheap med online without prescription visit site',
 'claim free vacation package limited time offer',
 'selected cash prize reply win claim',
 'urgent account compromised click link secure',
 'pre approved loan apply',
 'let catch coffee sometime',
 'congratulation walmart gift card click claim',
 'congratulation walmart gift card click claim',
 'get cheap med online without prescription visit site',
 'call back free',
 'get cheap med online without prescription visit site',
 'congratulation walmart gift card click claim',
 'earn day working home experience required',
 'let catch coffee sometime',
 'subscription ending renew avoid interruption',
 'late traffic really bad right',
 'forget bring document meeting',
 'hey still lunch today',
 'earn day working home experience required',
 'pre approved loan apply',
 'pre approved loan apply',
 'get cheap med online without prescription visit site',
 'happy birthday hope great day',
 'selected cash prize reply win claim',
 'thanks help earlier',
 'forget bring document meeting',
 'meeting rescheduled pm',
 'selected cash prize reply win claim',
 'get cheap med online without prescription visit site',
 'meeting rescheduled pm',
 'worry everything fine',

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(max_features=1000)

In [ ]:
X = tfidf.fit_transform(corpus).toarray()

In [ ]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.57735027],
       [0.        , 0.53274258, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
tfidf = TfidfVectorizer(max_features=1000,ngram_range=(2,2))

In [ ]:
X = tfidf.fit_transform(corpus).toarray()

In [ ]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.70710678],
       [0.        , 0.57735027, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
tfidf.vocabulary_

{'claim free': 13,
 'free vacation': 28,
 'vacation package': 64,
 'package limited': 46,
 'limited time': 39,
 'time offer': 61,
 'meeting rescheduled': 44,
 'rescheduled pm': 55,
 'coming party': 17,
 'party tonight': 47,
 'call back': 8,
 'back free': 4,
 'happy birthday': 32,
 'birthday hope': 6,
 'hope great': 36,
 'great day': 31,
 'subscription ending': 59,
 'ending renew': 23,
 'renew avoid': 53,
 'avoid interruption': 3,
 'scam really': 56,
 'get cheap': 29,
 'cheap med': 12,
 'med online': 43,
 'online without': 45,
 'without prescription': 68,
 'prescription visit': 49,
 'visit site': 65,
 'urgent account': 63,
 'account compromised': 0,
 'compromised click': 18,
 'click link': 15,
 'link secure': 40,
 'thanks help': 60,
 'help earlier': 33,
 'let catch': 38,
 'catch coffee': 11,
 'coffee sometime': 16,
 'pre approved': 48,
 'approved loan': 2,
 'loan apply': 41,
 'forget bring': 26,
 'bring document': 7,
 'document meeting': 21,
 'worry everything': 70,
 'everything fine': 24,
 'hey still': 34,
 'still lunch': 58,
 'lunch today': 42,
 'late traffic': 37,
 'traffic really': 62,
 'really bad': 51,
 'bad right': 5,
 'congratulation walmart': 19,
 'walmart gift': 66,
 'gift card': 30,
 'card click': 9,
 'click claim': 14,
 'act receive': 1,
 'receive free': 52,
 'free iphone': 27,
 'selected cash': 57,
 'cash prize': 10,
 'prize reply': 50,
 'reply win': 54,
 'win claim': 67,
 'earn day': 22,
 'day working': 20,
 'working home': 69,
 'home experience': 35,
 'experience required': 25}

Spam_messages_Detaction_Task

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('spam_messages_1000.csv',encoding='latin-1')

In [ ]:
df

    label                                            message
0    spam  Claim your free vacation package now. Limited ...
1     ham                       Meeting rescheduled to 3 PM.
2     ham               Are you coming to the party tonight?
3    spam  Claim your free vacation package now. Limited ...
4     ham             Can you call me back when you're free?
..    ...                                                ...
995  spam  You have been selected for a cash prize. Reply...
996   ham  Don't forget to bring the documents for the me...
997   ham                      Thanks for your help earlier!
998   ham              Don't worry, everything will be fine.
999  spam               Act now to receive your free iPhone!

[1000 rows x 2 columns]

In [33]:
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer,RegexpStemmer,SnowballStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
df.columns = ['label','message']

In [ ]:
df.head

<bound method NDFrame.head of     label                                            message
0    spam  Claim your free vacation package now. Limited ...
1     ham                       Meeting rescheduled to 3 PM.
2     ham               Are you coming to the party tonight?
3    spam  Claim your free vacation package now. Limited ...
4     ham             Can you call me back when you're free?
..    ...                                                ...
995  spam  You have been selected for a cash prize. Reply...
996   ham  Don't forget to bring the documents for the me...
997   ham                      Thanks for your help earlier!
998   ham              Don't worry, everything will be fine.
999  spam               Act now to receive your free iPhone!

[1000 rows x 2 columns]>

In [ ]:
df.head()

  label                                            message
0  spam  Claim your free vacation package now. Limited ...
1   ham                       Meeting rescheduled to 3 PM.
2   ham               Are you coming to the party tonight?
3  spam  Claim your free vacation package now. Limited ...
4   ham             Can you call me back when you're free?

In [ ]:
df['label'].value_counts()

label
ham     512
spam    488
Name: count, dtype: int64

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r"\d+","",text)
    text = [lemmatizer.lemmatize(word) for word in text.split() if word not in stop_words and word not in string.punctuation]
    text = ' '.join(text)
    return text

df['cleaned_message'] = df['message'].apply(clean_text)
df[['message', 'cleaned_message']]

                                               message                                    cleaned_message
0    Claim your free vacation package now. Limited ...  claim free vacation package now. limited time ...
1                         Meeting rescheduled to 3 PM.                            meeting rescheduled pm.
2                 Are you coming to the party tonight?                              coming party tonight?
3    Claim your free vacation package now. Limited ...  claim free vacation package now. limited time ...
4               Can you call me back when you're free?                                    call back free?
..                                                 ...                                                ...
995  You have been selected for a cash prize. Reply...              selected cash prize. reply win claim.
996  Don't forget to bring the documents for the me...                     forget bring document meeting.
997                      Thanks for your help earlier!                               thanks help earlier!
998              Don't worry, everything will be fine.                            worry, everything fine.
999               Act now to receive your free iPhone!                           act receive free iphone!

[1000 rows x 2 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['label_num'] = le.fit_transform(df['label'])

In [ ]:
df

    label  ... label_num
0    spam  ...         1
1     ham  ...         0
2     ham  ...         0
3    spam  ...         1
4     ham  ...         0
..    ...  ...       ...
995  spam  ...         1
996   ham  ...         0
997   ham  ...         0
998   ham  ...         0
999  spam  ...         1

[1000 rows x 4 columns]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=100,ngram_range=(2,3))
X = tfidf.fit_transform(df['cleaned_message']).toarray()

In [ ]:
X

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.4472136, ..., 0.       , 0.       ,
        0.       ]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
Y = df['label_num']
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state=40)

In [ ]:
x_train

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.25819889, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
model = MultinomialNB()
model.fit(x_train,y_train)
y_pred = model.predict(x_text)
y_pred

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1])

In [ ]:
accuracy_score(y_test,y_pred)

0.91

In [ ]:
confusion_matrix(y_test,y_pred)

array([[103,   0],
       [ 18,  79]], dtype=int64)

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92       103
           1       1.00      0.81      0.90        97

    accuracy                           0.91       200
   macro avg       0.93      0.91      0.91       200
weighted avg       0.92      0.91      0.91       200

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [ ]:
logreg = LogisticRegression()
logreg.fit(x_train,y_train)

LogisticRegression()

In [ ]:
print(logreg.score(x_test,y_test))

0.91

In [ ]:
# def predict_message(msg):
#     cleaned = clean_text(msg)
#     vector = tfidf.transform([cleaned])
#     print(vector)
#     pred_ans = model.predict(vector)
#     return 'Spam' if pred_ans[0] == 1 else 'Ham'


# predict_message("hello world")

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

# Step 1: Preprocessing already done
X = df['cleaned_message']
y = df['label_num']

# Step 2: Fit vectorizer on all training data
tfidf = TfidfVectorizer(max_features=100)
X_tfidf = tfidf.fit_transform(X)

# Step 3: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

# Step 4: Train the model
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [ ]:
def predict_message(msg):
    cleaned = clean_text(msg)
    vector = tfidf.transform([cleaned])  
    print(vector)
    pred_ans = model.predict(vector)
    return 'Spam' if pred_ans == 1 else 'Ham'

predict_message("WIN CASE")

  (0, 81)	1.0

'Spam'

In [30]:
df = pd.read_csv('IMDB Dataset.csv')
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [31]:
## Clearn Data
from bs4 import BeautifulSoup
from textblob import TextBlob

def remove_html(text):
    return BeautifulSoup(text,"html.parser").get_text()

def remove_emojis(text):
    return text.encode('ascii','ignore').decode('ascii')

def correct_spelling(text):
    return str(TextBlob(text).correct())

In [ ]:
pip install bs4 textblob

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Collecting textblob
  Downloading textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)
Collecting beautifulsoup4 (from bs4)
  Using cached beautifulsoup4-4.13.4-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: nltk>=3.9 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk>=3.9->textblob) (8.2.1)
Requirement already satisfied: joblib in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk>=3.9->textblob) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk>=3.9->textblob) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Collecting soupsieve>1.2 (from beautifulsoup4->bs4)
  Using cached soupsieve-2.7-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from beautifulsoup4->bs4) (4.14.0)
Requirement already satisfied: colorama in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Downloading textblob-0.19.0-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------------------------------- 624.3/624.3 kB 5.8 MB/s eta 0:00:00
Using cached beautifulsoup4-4.13.4-py3-none-any.whl (187 kB)
Using cached soupsieve-2.7-py3-none-any.whl (36 kB)
Installing collected packages: soupsieve, beautifulsoup4, textblob, bs4

   ---------- ----------------------------- 1/4 [beautifulsoup4]
   ---------- ----------------------------- 1/4 [beautifulsoup4]
   ---------- ----------------------------- 1/4 [beautifulsoup4]
   ---------- ----------------------------- 1/4 [beautifulsoup4]
   -------------------- ------------------- 2/4 [textblob]
   -------------------- ------------------- 2/4 [textblob]
   -------------------- ------------------- 2/4 [textblob]
   ---------------------------------------- 4/4 [bs4]

Successfully installed beautifulsoup4-4.13.4 bs4-0.0.2 soupsieve-2.7 textblob-0.19.0
Note: you may need to restart the kernel to use updated packages.

In [34]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
reviews = []
def clearn_text(text):
    text = text.lower()
    text = re.sub(r'\d+',"",text)
    text = [lemmatizer.lemmatize(word) for word in text.split() if word not in stop_words and word not in string.punctuation]
    text = ' '.join(text)
    return text

df['clearn_review'] = df['review'].apply(clearn_text)

In [35]:

df['clearn_review'] = df['clearn_review'].apply(remove_html)
df['clearn_review'] = df['clearn_review'].apply(remove_emojis)

In [ ]:
# pip install cleantext

Collecting cleantext
  Downloading cleantext-1.1.4-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: nltk in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from cleantext) (3.9.1)
Requirement already satisfied: click in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk->cleantext) (8.2.1)
Requirement already satisfied: joblib in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk->cleantext) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk->cleantext) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from nltk->cleantext) (4.67.1)
Requirement already satisfied: colorama in c:\users\admin\desktop\ai-ml_qb\gen_ai\.venv\lib\site-packages (from click->nltk->cleantext) (0.4.6)
Downloading cleantext-1.1.4-py3-none-any.whl (4.9 kB)
Installing collected packages: cleantext
Successfully installed cleantext-1.1.4
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# from cleantext import clean

# def clean_using_lib(text):
#     return clean(text)
                
# df['clearn_review'] = df['clearn_review'].apply(clean_using_lib)

In [36]:
df

,review,sentiment,clearn_review
0,One of the other reviewers has mentioned that ...,positive,one reviewer mentioned watching oz episode hoo...
1,A wonderful little production. <br /><br />The...,positive,wonderful little production. the filming techn...
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,negative,basically there's family little boy (jake) thi...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,"petter mattei's ""love time money"" visually stu..."
...,...,...,...
49995,I thought this movie did a down right good job...,positive,thought movie right good job. creative origina...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,"bad plot, bad dialogue, bad acting, idiotic di..."
49997,I am a Catholic taught in parochial elementary...,negative,catholic taught parochial elementary school nu...
49998,I'm going to have to disagree with the previou...,negative,going disagree previous comment side maltin on...
49999,No one expects the Star Trek movies to be high...,negative,"one expects star trek movie high art, fan expe..."

In [61]:
tfidf = TfidfVectorizer(max_features = 1702,ngram_range=(2,3))
X = tfidf.fit_transform(df['clearn_review']).toarray()

In [62]:
print(X.shape)

(50000, 1702)

In [63]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['sentiment_num'] = label_encoder.fit_transform(df['sentiment'])

In [64]:
df

,review,sentiment,clearn_review,sentiment_num
0,One of the other reviewers has mentioned that ...,positive,one reviewer mentioned watching oz episode hoo...,1
1,A wonderful little production. <br /><br />The...,positive,wonderful little production. the filming techn...,1
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...,1
3,Basically there's a family where a little boy ...,negative,basically there's family little boy (jake) thi...,0
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,"petter mattei's ""love time money"" visually stu...",1
...,...,...,...,...
49995,I thought this movie did a down right good job...,positive,thought movie right good job. creative origina...,1
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,"bad plot, bad dialogue, bad acting, idiotic di...",0
49997,I am a Catholic taught in parochial elementary...,negative,catholic taught parochial elementary school nu...,0
49998,I'm going to have to disagree with the previou...,negative,going disagree previous comment side maltin on...,0
49999,No one expects the Star Trek movies to be high...,negative,"one expects star trek movie high art, fan expe...",0

In [65]:
df.sample(10)

,review,sentiment,clearn_review,sentiment_num
30940,So we compromised. This was a fairly charming ...,positive,"compromised. fairly charming film, liked art d...",1
37618,Holy @#%& this movie was still warm and juicy ...,negative,holy @#%& movie still warm juicy pile made wit...,0
34051,This is the first time I ever saw a movie with...,negative,"first time ever saw movie jamie foxx, bet last...",0
14592,First i will say that i am going to be as subj...,negative,first say going subjective can.there potential...,0
47108,"I, like so many others on here, bought this mo...",negative,"i, like many others here, bought movie local w...",0
17367,"Though the story is essentially routine, and t...",positive,"though story essentially routine, ""surprise"" e...",1
21574,"The Honey, I Shrunk the Kids franchise was a h...",negative,"honey, shrunk kid franchise huge deal mention ...",0
32058,"Although the acting was excellent, I spent the...",negative,"although acting excellent, spent whole movie w...",0
44790,Murders are occurring in a Texas desert town. ...,negative,murder occurring texas desert town. responsibl...,0
4950,Joe D'Amato might have made some other notable...,negative,joe d'amato might made notable movie long prol...,0

In [66]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
x_train,x_test,y_train,y_test = train_test_split(X,df['sentiment_num'],test_size=0.1,random_state=50)

In [67]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [68]:
model = MultinomialNB()

In [69]:
model.fit(x_train,y_train)

MultinomialNB()

In [70]:
y_pred = model.predict(x_test)

In [71]:
y_pred

array([1, 0, 0, ..., 1, 0, 0])

In [72]:
accuracy_score(y_test,y_pred)

0.7754

In [73]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.75      0.77      2507
           1       0.76      0.80      0.78      2493

    accuracy                           0.78      5000
   macro avg       0.78      0.78      0.78      5000
weighted avg       0.78      0.78      0.78      5000

In [74]:
confusion_matrix(y_test,y_pred)

array([[1873,  634],
       [ 489, 2004]], dtype=int64)

In [75]:
from nltk.tokenize import word_tokenize
maxi = 0
for i in df['clearn_review']:
    j = word_tokenize(i)
    if(len(j) > maxi):
        maxi = len(j)
print(maxi)

1702